#!/bin/sh

. /usr/share/debconf/confmodule

set -e

dev=$1
id=$2
part=$dev/$id

cd $dev

[ -f $part/method -a -f $part/acting_filesystem ] || exit 0

filesystem=$(cat $part/acting_filesystem)

choice_mountpoint () {
    case "$filesystem" in
	ext3)
	    db_metaget partman-ext3/text/specify_mountpoint description
	    printf "mountpoint\t${RET}\n"
	    ;;
    esac
}

choice_options () {
    case "$filesystem" in
	ext3)
	    db_metaget partman-ext3/text/options description
	    printf "options\t$RET\n"
	    ;;
    esac
}

choice_mountpoint

choice_options

