.TH lmod-detect-pci 1

.SH NAME
lmod-detect-pci \- Determine linux (a.k.a the kernel) modules required to support your PCI hardware.

.SH DESCRIPTION
.PP
\fIlmod-detect-pci\fP uses libpci to scan your local hardware, it then uses an internal table to determine the correct kernel module to support each device.

.SH SEE ALSO
lspci

.SH BUGS
Unknown so far, please let me know if you find any.

.SH AUTHOR
Glenn McGrath <bug1@debian.org>

