#!/bin/sh

. /usr/share/debconf/confmodule

# Only run at >= high priority the first time.
if [ -f /var/lib/partman/initial_auto ]; then
	exit 0
fi
db_get debconf/priority
if [ "$RET" != high ] && [ "$RET" != critical ]; then
	exit 0
fi
[ -d /var/lib/partman ] || mkdir /var/lib/partman
touch /var/lib/partman/initial_auto

. /lib/partman/definitions.sh
ask_user /lib/partman/automatically_partition || true
