#!/bin/sh

. /lib/partman/definitions.sh

dev=$2
oldid=$3

cd $dev

open_dialog GET_RESIZE_RANGE $oldid
read_line minsize cursize maxsize
close_dialog

[ "$maxsize" ] || exit 1

hminsize=$(longint2human $minsize)
hcursize=$(longint2human $cursize)
hmaxsize=$(longint2human $maxsize)

db_set partman-partitioning/confirm_resize 'false'
db_fset partman-partitioning/confirm_resize seen false
db_input high partman-partitioning/confirm_resize || true
db_go || exit 0
db_get partman-partitioning/confirm_resize

[ "$RET" = 'true' ] || exit 0

ask_for_size () {
    local noninteractive
    noninteractive=true
    while true; do
	newsize=''
	while [ ! "$newsize" ]; do
	    db_set partman-partitioning/new_size "$hcursize"
	    db_fset partman-partitioning/new_size seen false
	    db_subst partman-partitioning/new_size MINSIZE "$hminsize"
	    db_subst partman-partitioning/new_size MAXSIZE "$hmaxsize"
	    db_input high partman-partitioning/new_size || $noninteractive
	    noninteractive="return 1"
	    db_go || return 1
	    db_get partman-partitioning/new_size
	    if valid_human "$RET"; then
		hnewsize="$RET"
		newsize=$(human2longint "$hnewsize")
	    else
		db_fset partman-partitioning/bad_new_size seen false
		db_input high partman-partitioning/bad_new_size || true
		db_go || true
	    fi
	done
	if perform_resizing; then break; fi
    done
    return 0
}

perform_resizing () {
    for s in /lib/partman/commit.d/*; do
	if [ -x $s ]; then
	    $s || {
		db_fset partman-partitioning/new_size_commit_failed seen false
		db_input high partman-partitioning/new_size_commit_failed || true
		db_go || true
		exit 100
	    }
	fi
    done

    name_progress_bar partman-partitioning/progress_resizing
    open_dialog RESIZE_PARTITION $oldid $newsize
    read_line newid
    close_dialog

    if [ -n "$newid" -a "$newid" != "$oldid" ]; then
	[ ! -e "$newid" ] || rm -rf $newid
	mkdir $newid
	cp -r $oldid/* $newid/
	
	for s in /lib/partman/init.d/*; do
	    if [ -x $s ]; then
		$s || exit 100
	    fi
	done
    fi
}

ask_for_size
exit 100
