#!/bin/sh

. /usr/share/debconf/confmodule

dev="$1"
id=$2
cd $dev

[ -f $id/method ] || exit 0

method=$(cat $id/method)

if [ $(cat $dev/$id/available_filesystems | wc -l) -ge 2 ]; then
    if [ -f $id/filesystem ]; then
	fs=$(cat $id/filesystem)
	RET=''
	db_metaget partman/filesystem_long/"$fs" description || RET=''
	fs=${RET:-$fs}
    else
	db_metaget partman-target/text/no_file_system description
	fs="$RET"
    fi
    
    db_metaget partman-target/text/choose_filesystem description
    printf "fs\t%-25s%s\n" "${RET}" "$fs"
fi

