#!/bin/sh

. /lib/partman/definitions.sh

dev=$1
id=$2
property=$3

# The imaginery file system "lvm" is available only for lvm partitions
[ -f $id/method ] || exit 0
method=$(cat $id/method)
if [ "$method" = lvm ]; then
    echo lvm
fi
