#!/bin/sh
# Scan a whole tree for translations.
set -e
for dir in $(find $1 -type d | grep /debian\$ |grep -v svn); do
	base=$(echo $dir | sed 's/\/debian$//');
	if SCAN_TRANS=1 scripts/l10n/output-l10n-changes -d $base; then
		if head -n 1 $dir/changelog | grep -q UNRELEASED; then
			echo "   (Plus other UNRELEASED changes.)"
		fi
	fi
done
