#!/bin/sh
#
# Script for switching a given language to the "single file" model
# (using only one file in packages/po)
#
# This should only be used ONCE for a given language
#
# Switching to multipld files omdel only need to remove the file
# in packages/po

usage() {
echo  "Usage:"
echo  "$0 <lang> <D-I repository path>"
}

if [ -z "$2" ]
then
  usage
  exit 1
fi

LANG=$1
DI_COPY=$2

# A few checks about the D-I copy directory
if [ ! -d $DI_COPY ] ; then
  echo $DI_COPY does not exist
  exit 1
fi

if [ ! -d $DI_COPY/.svn ] ; then
  echo No $DI_COPY/.svn directory found
  echo $DI_COPY may not be a copy of Debian Installer SVN repository
  exit 1
fi

if ! grep "svn/d-i/trunk" $DI_COPY/.svn/entries >/dev/null 2>&1 ; then
  echo $DI_COPY does not seem to be a complete Debian Installer SVN copy
  echo Please check it before...
  exit 1
fi

if [ ! -f $DI_COPY/packages/languagechooser/debian/po/$LANG.po ] ; then
  echo No translation found for languagechooser in $LANG
  echo Are you sure that $LANG is an existing D-I translation?
  exit 1
fi

echo $LANG
echo $DI_COPY

echo This script is not finished yet.

