#!/bin/bash
# Copyright (c) 2004-2006 Dennis Stampfer <seppy@debian.org>
# Copyright (c) 2006 Christian Perrier <bubulle@debian.org>
# Licensed under the GNU General Public License
#
# Fetches sources for the installer packages and generates
# some translation-related statistics.
#
# Files:
#   o packages-list
#     Names of the packages to download
#   o languages 
#     what languages to be checked?
#   o paths
#     where are the po-files located in this package?
#     (sometimes more than one, like shadow)
#
#   o packages (folder)
#     The packages get downloaded into $TEMPFILE, cleaned up
#     and moved to packages/.
# 
#

############################### Functions ##################################
fancy_output() {
	echo "==============================================================================="
}

create_dir() {
  if [ ! -d "$1" ] ; then
    if [ ! -e "$1" ] ; then
      mkdir -p "$1"
    else
      echo "$1" already exists and is not a directory
    fi
  fi
}

usage(){
  echo Usage: $0 level [config] [fetch]
  echo 
  echo  "               level: the D-I \"level\" to work on"
  echo  "               config: optional config file"
  echo  "               fetch: fetch translations from repositories"
}

translated () {  #how many are translated?
  $GETTEXT/msgfmt -o /dev/null --statistics $1 2>&1  | sed -e 's/, //g' | $WD/scripts/rmnl 2|sed -e 's/\.//g'|grep " translated"|sed -e 's/ .*$//g'
}


fuzzy() {  #how many fuzzy?
  #msgfmt -o /dev/null --statistics  $WD/$1 2>&1 | sed -e 's/.*translated messages, //g' |sed -e 's/ fuzzy.*$//g'
  $GETTEXT/msgfmt -o /dev/null --statistics $1 2>&1 | sed -e 's/, /§/g'|$WD/scripts/rmnl 2|sed -e 's/\.//g'|grep " fuzzy"|sed -e 's/ .*$//g'
}

untranslated () {  #guess, what does this do?
  #msgfmt -o /dev/null --statistics $WD/$1 2>&1|sed -e 's/.*, //g' | sed -e 's/ .*.$//g'
  $GETTEXT/msgfmt -o /dev/null --statistics $1 2>&1 | sed -e 's/, /§/g'|$WD/scripts/rmnl 2|sed -e 's/\.//g'|grep " untranslated"|sed -e 's/ .*$//g'
}

translator () { #who is last-translator?
  #awk '/Last-Translator:/ { print $2,$3 } ' $1
  grep "Last-Translator: " $1 | sed -e 's/"Last-Translator: //g' | sed -e 's/ <.*$//g'
}

print_text () { # print standard-text
echo -n "Files fetched and report generated on: " >> $TARGET_DIR/$lang.txt
date -u  >> $TARGET_DIR/$lang.txt
echo "

Read: http://people.debian.org/~seppy/d-i/translation-status.html" >> $TARGET_DIR/$lang.txt
}
########################### End of functions ##################################



########################### Defaults ##########################################
WD="."
FETCH=""
GETTEXT="/usr/bin"
LEVEL=1
########################### End of Defaults ###################################


##########################  Command line parsing ##############################
if [ "$3" = "fetch" ] ; then
  FETCH=Y
fi

if [ "$2" ] ; then
  CONFIG=$2
fi

if [ "$1" ] ; then
  LEVEL=$1
else
  usage
  exit 1
fi

if [ "$CONFIG" ] ; then
  if [ -r "$CONFIG" ] ; then
    . "$CONFIG"
  else
    echo $CONFIG does not exist or unreadable
    exit 1
  fi
fi
########################## End of command line parsing ###################

########################## Definitions, which depend on command-line #####
# Directory with config files
CONFIG_DIR=$WD/config
# Directory for results
RESULTS_DIR=$WD/results
# Directory for graphs (translation ratio over time)
GRAPHS_DIR=$WD/graphs
# Directory for lock files and other temporary stuff
RUN_DIR=$WD/run

SCRIPTNAME="level $LEVEL"
COPY_TO_DIR=$WD/material/level$LEVEL
TARGET_DIR=$RESULTS_DIR/level$LEVEL
GRAPH_FILE=".l${LEVEL}.dat"

export PATH=$GETTEXT:$PATH

TEMPDIR="${RUN_DIR}/gen-stats-temp-$RANDOM"
export GETTEXT
LANG=C
########################## End of definitions ############################

########################## Sanity and consistency checks #################

# Here we'll need to add some sanity check on LEVEL

if [ ! -d "$GETTEXT" ] ; then
  echo $GETTEXT is not a directory
  exit 1
fi

if [ ! -x "$GETTEXT/msgfmt" -o ! -x "$GETTEXT/msgmerge" -o ! -x "$GETTEXT/debconf-updatepo" ] ; then
  echo Missing gettext utilities in $GETTEXT
  exit 1
fi

# Create all the needed directories (safely)
create_dir $WD
create_dir $TARGET_DIR
create_dir $CONFIG_DIR
create_dir $RESULTS_DIR
create_dir $TARGET_DIR/POT
create_dir $COPY_TO_DIR
create_dir $RUN_DIR
create_dir $GRAPHS_DIR/data

PROSPECTIVE="$WD/material/packages.unstable1/debian-installer/packages/po/PROSPECTIVE"
if [ ! -f $PROSPECTIVE ] ; then
  echo No PROSPECTIVE file found
  echo Please run $0 at least once for level 1 with \"fetch\"
  exit 1
fi

LANG_NAMES="$WD/config/languages.names"
if [ ! -f "${LANG_NAMES}" ] ; then
  echo "No language names file (${LANG_NAMES}) found"
  exit 1
fi

if [ -f "${RUN_DIR}/$LEVEL.lock" ]; then
	echo "A lockfile ${RUN_DIR}/$LEVEL.lock exists. Exiting..." 1>&2
	exit 1
fi
############### End of sanity and consistency checks #############


############### THE REAL BEGINNING ###############################

# Create the lock file
cd $WD
touch "${RUN_DIR}/$LEVEL.lock"

# Create the directories for the material
create_dir $WD/material/packages.unstable$LEVEL
create_dir $WD/material/packages.testing$LEVEL

# Some output
echo -n "$SCRIPTNAME script start by user $USER, logname $LOGNAME: "
date

## echo "Working directory is $WD"
## echo "Skipping in rank.txt:"
## grep -v "^#" $PROSPECTIVE

rm -rf $TARGET_DIR/*
if [ "$FETCH" ]; then
	for I in `find $WD/material/packages$LEVEL/ -name "*.po"`; do 
		rm $I
	done
fi

fancy_output

#get sources:
if [ "$FETCH" ]; then
	echo "Sources fetched via apt:"
	
	rm -rf $TEMPDIR > /dev/null

	#get files:
	mkdir $TEMPDIR
	cd $TEMPDIR

	for dist in testing unstable ; do
		date -u >> $TARGET_DIR/packages-list-$dist
		echo "  From $dist:"
		echo "From $dist:" >> $TARGET_DIR/packages-list-$dist
		for pkg in `cat $WD/config/packages.$dist$LEVEL`; do
			cd $TEMPDIR
  			echo -n "    $pkg..."
			rm -rf $WD/material/packages.$dist$LEVEL/$pkg*
	  		apt-get $APT_OPT -t $dist source $pkg > /dev/null || echo "FAILED to fetch $pkg from $dist!" >> $TARGET_DIR/packages-list-$dist
	  		rm -f *.tar.gz *.dsc *.diff.gz
			
#			create_dir $WD/material/packages.$dist$LEVEL/$pkg
  			mv * $WD/material/packages.$dist$LEVEL/$pkg
			if [ "$pkg" = "newt" ]; then
				cd $WD/material/packages.$dist$LEVEL/$pkg/
				tar -xzf *.tar.gz
				#cat debian/patches/05_whiptail_i18n.patch debian/patches/85_more_i18n.patch | patch -p0
				cat debian/patches/* | patch -p0 >/dev/null
				rm *.tar.gz
				mv newt-* newt
				cd newt/po/
				make newt.pot >/dev/null
				chmod a+r newt.pot
			fi
			head -n 1 $WD/material/packages.$dist$LEVEL/$pkg/debian/changelog >> $TARGET_DIR/packages-list-$dist
  			echo "Done."
		done
	done

	fancy_output

	
	#get files from CVS:
	echo "Sources fetched from CVS/SVN for unstable statistics:"
	cd $WD/material/packages.unstable$LEVEL/
#	cat $WD/config/packages.cvs$LEVEL

	sh $WD/config/packages.cvs.commands$LEVEL
	echo -e "\nFrom CVS/SVN:" >> $TARGET_DIR/packages-list-unstable
	cat $WD/config/packages.cvs$LEVEL >> $TARGET_DIR/packages-list-unstable

	## echo "Finished getting files!"
	cd $WD
else
	#ls packages/* 2&> /dev/null || exit
	echo "no download... (use 'fetch' to force)"

	for dist in unstable testing ; do
		date -u > $TARGET_DIR/packages-list-$dist
		echo "From $dist:" >> $TARGET_DIR/packages-list-$dist
		for pkg in `cat $WD/config/packages.$dist$LEVEL`; do
			head -n 1 $WD/material/packages.$dist$LEVEL/$pkg/debian/changelog >> $TARGET_DIR/packages-list-$dist
		done
	done

	echo -e "\nFrom CVS/SVN:" >> $TARGET_DIR/packages-list-unstable
	cat $WD/config/packages.cvs$LEVEL >> $TARGET_DIR/packages-list-unstable

fi

fancy_output

echo "Computing the number of strings:"

for dist in testing unstable ; do
	echo "  In $dist:"
	#check how many strings at all
	TOTALU=0
	LANG=C
	mkdir -p $TARGET_DIR/POT
	for path in `cat $WD/config/paths.$dist$LEVEL`; do
		test -f $WD/material/packages.$dist$LEVEL/$path/*.pot || continue
		U=`untranslated $WD/material/packages.$dist$LEVEL/$path/*.pot`
		
		# Copy files only for unstable
		if [ "$dist" = "unstable" ] ; then
			cp $WD/material/packages.$dist$LEVEL/$path/*.pot $TARGET_DIR/POT/${path//\//_}.pot
		fi
		
	  	echo "      $path/*.pot:  $U"

		TOTALU=`expr $TOTALU + $U || echo 0`
		if [ "$TOTALU" = "0" -o -z "$TOTALU" ]; then
			echo "Error while counting untranslated strings in templates."
			$GETTEXT/msgfmt --statistics $WD/material/packages.$dist$LEVEL/$path/*.pot
			#	exit
		fi

		#backup everylanguage-file to check against debconf-updatepo later
		for lang in `cat $WD/config/languages`; do
			test -f $WD/material/packages.$dist$LEVEL/$path/$lang.po || continue
			cp $WD/material/packages.$dist$LEVEL/$path/$lang.po $WD/material/packages.$dist$LEVEL/$path/$lang.po.orig >/dev/null 2>&1
		done

		(export PODEBCONF_LIB=/home/bubulle/share/intltool-debian; cd $WD/material/packages.$dist$LEVEL/$path/; pwd | grep "debian/po" > /dev/null && ~bubulle/bin/debconf-updatepo-sid )


	done
	echo "    Total: $TOTALU"
done

fancy_output

wget -q -O $WD/material/spellcheck${LEVEL}.txt http://d-i.alioth.debian.org/spellcheck/level${LEVEL}/latest/stats.txt || echo "Could not fetch spellcheck stats file for level $I."

mkdir $TARGET_DIR/files
rm -f $TARGET_DIR/.rank.txt$LEVEL
rm -rf $TEMPDIR


for dist in testing unstable ; do
	echo "Computing languages statistics for $dist:"
	if [ "$dist" = "unstable" ] ; then
		ext=""
	else
		ext=".$dist"
	fi

	RANK=""

	#following 3 variables for generating the graph. they include all
	#strings of all languages of all packages
	GR_TRANSLATED=0
	GR_FUZZY=0
	GR_UNTRANSLATED=0
	for lang in `cat $WD/config/languages`; do #run for every language
		echo -n "  $lang	..."
		NAME=`cat $LANG_NAMES | grep "$lang:" | sed "s/://g" || echo $lang`
		echo -e "Statistics of $SCRIPTNAME packages for $NAME:\nRead http://people.debian.org/~seppy/d-i/translation-status.html\n\nOutdated:" >>  $TARGET_DIR/$lang$ext.txt
		MISSING=""

		#for total strings of a language
		TU=0
		TT=0
		TF=0
		for path in `cat config/paths.$dist$LEVEL`; do #for every package
			if [ -e $WD/material/packages.$dist$LEVEL/$path/$lang.po ]; then #if the file does exist
				LASTT=`translator $WD/material/packages.unstable$LEVEL/$path/$lang.po`
				
				$GETTEXT/msgmerge -U $WD/material/packages.$dist$LEVEL/$path/$lang.po $WD/material/packages.$dist$LEVEL/$path/*.pot > /dev/null 2>&1
      				SIGNS="  "	
				#now check if a file has been modified by debconf-updatepo and output a *
				#for lang in `cat $WD/languages`; do
				#	test -f packages/$path/$lang.po || continue
				ORIG=`$GETTEXT/msgfmt --statistics $WD/material/packages.$dist$LEVEL/$path/$lang.po.orig 2>&1`
				NEW=`$GETTEXT/msgfmt --statistics $WD/material/packages.$dist$LEVEL/$path/$lang.po 2>&1`
				if [ "$ORIG" != "$NEW" ]; then
					SIGNS="$SIGNS*" #>> $TARGET_DIR/$lang.txt
				fi
				#rm -f $WD/material/packages.$dist$LEVEL/$path/$lang.po.orig 
	
				#done
     				$GETTEXT/msgfmt $WD/material/packages.$dist$LEVEL/$path/$lang.po > /dev/null 2>&1|| (echo "$SIGNS!$path/$lang.po [$LASTT]" >> $TARGET_DIR/$lang.txt; touch /tmp/.$LEVEL.error; return 1) || continue

				#strings of this package:
      				U=`untranslated $WD/material/packages.$dist$LEVEL/$path/$lang.po`
      				F=`fuzzy $WD/material/packages.$dist$LEVEL/$path/$lang.po`
     				T=`translated $WD/material/packages.$dist$LEVEL/$path/$lang.po`
      				test -z "$U" && U=0
      				test -z "$F" && F=0
      				test -z "$T" && T=0


      				#get infos:
				TU=`expr $TU + $U`
      				TT=`expr $TT + $T`
      				TF=`expr $TF + $F`


				#for the graph:
				GR_TRANSLATED=`expr $GR_TRANSLATED + $TT`
				GR_UNTRANSLATED=`expr $GR_UNTRANSLATED + $TU`
				GR_FUZZY=`expr $GR_FUZZY + $TF`
      			
				#dont show completely translated files:
      				if [ "$U" = "0" -a "$F" = "0" ]; then
         				OK="  $path/$lang.po $T"t" [$LASTT]\n$OK"
					echo -n
				else
      					echo "  $SIGNS$path/$lang.po: $T"t"$F"f"$U"u" [$LASTT]" >> $TARGET_DIR/$lang.txt
      				fi
			
			
				#copy (updated) files so that they can be translated:
				# Only do it for unstable
				if [ -z "$ext" ] ; then
					test -d $TARGET_DIR/files/$lang/ || mkdir $TARGET_DIR/files/$lang/
					cp $WD/material/packages.$dist$LEVEL/$path/$lang.po $TARGET_DIR/files/$lang/${path//'\/'/'_'}"_$lang.po"
				fi

				mv $WD/material/packages.$dist$LEVEL/$path/$lang.po.orig $WD/material/packages.$dist$LEVEL/$path/$lang.po >/dev/null 2>&1
    			else #=if not existing
				MISSING_U=`untranslated $WD/material/packages.$dist$LEVEL/$path/*.pot`
				test -z $MISSING_U && MISSING_U=0
      				MISSING="$MISSING  $path/$lang.po "$MISSING_U"u\n"
      				#echo "  !!$path/$lang.po"
    			fi

		done #for path in `cat paths`; do
 
	 	echo -e "\nTranslated:" >> $TARGET_DIR/$lang$ext.txt
		echo -e "$OK" >> $TARGET_DIR/$lang$ext.txt
		OK=""

  		echo -e "Missing files:\n$MISSING\n" >>  $TARGET_DIR/$lang$ext.txt
		if [ "$TOTALU" != 0 ] ; then
			P=`echo "$TT * 100 / $TOTALU"|bc`
		else
		P=0
		fi
	  	STR=`echo "$TT + $TU + $TF" | bc`	
	  	echo -e "Global statistics: "$TT"t"$TF"f"$TU"u ($P%)     (total strings: $TOTALU=100%)\n(From all $lang.po files)" >> $TARGET_DIR/$lang$ext.txt
	  	if [ "$STR" -gt "$TOTALU" ]; then
  			echo "  You have more strings translated/fuzzy/untranslated that in
  the pot-templates. Please check about that!" >>  $TARGET_DIR/$lang$ext.txt
	  	fi
	  	test -e /tmp/.$LEVEL.error && echo -e "SOME FILE(S) ARE CORRUPTED! Those are marked with \"!\".\n Run a \"msgfmt --check <po-file> to see what's wrong!\"" >>  $TARGET_DIR/$lang$ext.txt
		
		# generate ranking information
		LEAD="000";
	 	P="${LEAD:0:${#LEAD}-${#P}}$P"
		if [ ! `grep "^${lang}$" $PROSPECTIVE` ]; then
	 	   echo -en "$P%\t $lang" >> $TARGET_DIR/.rank.txt$LEVEL
  		   test -e /tmp/.$LEVEL.error && echo -n " SOME FILE(S) ARE CORRUPTED" >> $TARGET_DIR/.rank.txt$LEVEL
	  	   echo >> $TARGET_DIR/.rank.txt$LEVEL
		fi
	  	rm -f /tmp/.$LEVEL.error 


		# Data needed by graphs
		test "$P" = "000" || echo `date +%Y-%m-%d` $P >> $GRAPHS_DIR/data/$lang$GRAPH_FILE
	
	  	echo "Done. ($P%)"
		
	done # for lang...

done # for dist...

fancy_output

# Special info about the master file, for unstable only
if [ $LEVEL = 1 ]; then
	echo "Computing information for the master file..."
	for lang in `cat $WD/config/languages`; do #run for every language
		echo -n "  $lang...	"
		if [ -f $WD/material/packages.unstable1/debian-installer/packages/po/$lang.po ]; then
			MASTER_F=`fuzzy $WD/material/packages.unstable1/debian-installer/packages/po/$lang.po`
			MASTER_U=`untranslated $WD/material/packages.unstable1/debian-installer/packages/po/$lang.po`
			MASTER_T=`translated $WD/material/packages.unstable1/debian-installer/packages/po/$lang.po`
			echo "Master: "$MASTER_T"t"$MASTER_F"f"$MASTER_U"u" | tee -a $TARGET_DIR/$lang.txt
		else
			echo "No master file" | tee -a $TARGET_DIR/$lang.txt
		fi
	done
	fancy_output
fi

echo "Generating spellcheck information for unstable:"
# Add spellcheck info to the unstable files
for lang in `cat $WD/config/languages`; do #run for every language
	echo -n "  $lang	..."
	SPELLCHECK=`grep "$lang" $WD/material/spellcheck${LEVEL}.txt | sed "s/$lang //g"`
	if [ "$SPELLCHECK" != "" ]; then
		printf  "Spellcheck:
   %3s unknown words (-1 if no wordlist available)
   %3s wrong variables
   %3s codepoints
   %3s level-specific wrong msgstrs
" $SPELLCHECK >> $TARGET_DIR/$lang.txt
		echo "Done."
	else
		echo "No spellcheck available."  | tee -a  $TARGET_DIR/$lang.txt
	fi
  	print_text
done


	
# done
#for lang in `cat languages`; do

fancy_output

echo "Final steps:"

echo -n "  computing ranking information..."
# Generate ranking
echo "Rankings for $SCRIPTNAME packages." > $TARGET_DIR/rank.txt
date -u >> $TARGET_DIR/rank.txt
echo >> $TARGET_DIR/rank.txt
cp $TARGET_DIR/rank.txt $TARGET_DIR/rank-oldformat.txt
sort -r $TARGET_DIR/.rank.txt$LEVEL | sed 's/^00/  /g' | sed 's/^0/ /g' | cat -n  >> $TARGET_DIR/rank-oldformat.txt
$WD/scripts/sort-ranktxt < $TARGET_DIR/.rank.txt$LEVEL >> $TARGET_DIR/rank.txt
rm $TARGET_DIR/.rank.txt$LEVEL

echo "Done."

# Move files to their destination
cp $WD/config/HEADER.txt $TARGET_DIR/


echo -n "  Moving master files to a downloadable location..."
if [ $LEVEL = 1 ]; then
	mkdir $TARGET_DIR/master
	cp $WD/material/packages.unstable1/debian-installer/packages/po/* $TARGET_DIR/master

fi
echo "Done."

# Cleanup
echo -n "  Cleanup..."

rm -rf $COPY_TO_DIR
rm $WD/material/spellcheck${LEVEL}.txt
cp -r $TARGET_DIR $COPY_TO_DIR



rm -f $TARGET_DIR/.rank.txt$LEVEL
rm -rf $TEMPDIR
rm -rf messages messages.mo

chmod -R a+r $TARGET_DIR

rm $RUN_DIR/$LEVEL.lock

echo "Done."

fancy_output

echo -n "Script end: "
date

