#!/bin/bash
# Copyright (c) 2004-2006 Dennis Stampfer <seppy@debian.org>
# Copyright (c) 2006 Christian Perrier <bubulle@debian.org>
# Licensed under the GNU General Public License
#
# Generates overview files for D-I translation status
#
# NOT WORKING YET. This is currently seppy's script which I just commit in the SVN

LANG_LIST="/home/seppy/languages.names"
PROSPECT_FILE="packages1/debian-installer/packages/po/PROSPECTIVE"
if [ "$1" = "--prospective" ]; then
	LANGUAGES=$PROSPECT_FILE
	PROSPECTIVE=" *prospective*"
else
	LANGUAGES="/home/seppy/languages"
fi
cd /home/seppy/levels

date -u
echo "Complete list of$PROSPECTIVE languages and levels 1-4: (generated hourly)"
echo 

if [ -f *.lock ]; then
	echo "Lockfile found! Next run in +1h"
	exit
fi

CLEVEL[1]=0
CLEVEL[2]=0
CLEVEL[3]=0
CLEVEL[4]=0

for LANG in `grep -v "^#" $LANGUAGES`; do
    if [ "$1" != "--prospective" ]; then
    	grep "^$LANG" $PROSPECT_FILE > /dev/null && continue
    fi
    TOTAL=0
    cat $LANG_LIST | grep $LANG":" || echo $LANG:
    #echo -en "$LANG:\t"
    for LEVEL in `seq 4`; do
    	CURR=`cat level$LEVEL/$LANG.txt | grep "Global statistics:" | sed "s/^.*u (//g" | sed "s/%).*$//g"`
	echo -e "\t$LEVEL: $CURR%"
	TOTAL=`echo "scale=2;$TOTAL + $CURR" | bc`
	CLEVEL[$LEVEL]=`echo "scale=2; ${CLEVEL[$LEVEL]} + $CURR" | bc`
    done
    #echo -e "\n\t======="
    TOTAL=`echo "scale=2;$TOTAL / 4"|bc`
    echo -e "\t ->$TOTAL%<-"
    #echo -en "\t"
    if [ -f level1/master/$LANG.po ]; then
    	MASTER=`cat level1/$LANG.txt | grep "Master:"`
    	MASTERT=`echo $MASTER | sed -e "s/Master: //g" | sed -e "s/t.*//g"`
    	MASTERF=`echo $MASTER | sed -e "s/f.*//g"  | sed -e "s/.*t//g"`
    	test -z $MASTERF && MASTERF=0
    	MASTERU=`echo $MASTER | sed -e "s/.*f//g"  | sed -e "s/u//g";`
    	test -z $MASTERU && MASTERU=0
    	MASTERP=`echo "scale=4; (100 / ($MASTERT + $MASTERF + $MASTERU) ) * $MASTERT" | bc`
    	echo -e "\t$MASTER ($MASTERP%)"
    fi
    echo
done

LC=`cat $LANGUAGES | grep -v "^#" | wc -l | sed "s/ //g"`
if [ "$1" != "--prospective" ]; then
	PROS=`cat $PROSPECT_FILE | grep -v "^#" | wc -l | sed "s/ //g"`
	LC=`expr $LC - $PROS`
fi


CLEVEL[1]=`echo "scale=2;${CLEVEL[1]} / $LC" | bc`
CLEVEL[2]=`echo "scale=2;${CLEVEL[2]} / $LC" | bc`
CLEVEL[3]=`echo "scale=2;${CLEVEL[3]} / $LC" | bc`
CLEVEL[4]=`echo "scale=2;${CLEVEL[4]} / $LC" | bc`

echo "$LC languages listed: (English not included)"
echo "  Level1: ${CLEVEL[1]}%"
echo "  Level2: ${CLEVEL[2]}%"
echo "  Level3: ${CLEVEL[3]}%"
echo "  Level4: ${CLEVEL[4]}%"
TOTAL=`echo "scale=2;( ${CLEVEL[1]} + ${CLEVEL[2]} + ${CLEVEL[3]} + ${CLEVEL[4]} ) / 4" | bc`
echo "        ->$TOTAL%<-"



