#!/usr/bin/expect
# Just boot whatever is default in the boot loader.
spawn -noecho $env(CONSOLECOMMAND)

# Boot it. Not sure why I need multiple newlines, it sometimes seems to
# not see the first.
send "\r\r\r"

# Wait to make sure linux is really starting.
set timeout 360
expect -re "Linux version .* .*$"

exit
