#!/usr/bin/expect
# Just boot whatever is default in the boot loader.
spawn -noecho $env(CONSOLECOMMAND)

expect "boot: "

send "\r"

# Wait to make sure linux is really starting.
set timeout 360
expect -re "Linux version .* .*$"

exit
