#!/usr/bin/expect
# Expect script to boot from a CD on a proloant.

spawn -noecho $env(CONSOLECOMMAND)

set timeout 360

# This means that it's gotten to the boot menu.
expect "F12"

# This means that the CD has, presumably, now booted and the logo is
# showing.
expect "The Server is in Graphics Mode"

sleep 1

# Send a F1, which will get it out of graphics mode.
puts "OP"

sleep 2

send "$env(BOOTCOMMAND)\r"

set timeout 60
expect -re "booting.*kernel"

exit
