#!/usr/bin/perl
# Boot from disk on mips and wait for qemu to get ready.
use warnings;
use strict;
use Expect;
use POSIX 'setsid';

# Run in the background, because qemu won't begin accepting console input
# until the connection is made to its serial port, by console-qemu.
open STDIN, '/dev/null';
defined(my $pid = fork) or die "Can'fork: $!";
if ($pid) {
	sleep 2;
	exit;
}
setsid;

my $exp = new Expect;
#$exp->debug(2);
$exp->raw_pty(1);
$SIG{PIPE}=sub { die "SIGPIPE; exiting\n" };
$exp->spawn("startqemu-disk-mips") or die "running startqemu-disk-mips: $!";

$exp->expect(undef, "eof");
