#!/usr/bin/perl
# Make an sparc boot over serial console.
use Expect;
my $exp = new Expect;
#$exp->debug(2);
$exp->raw_pty(1);
$exp->spawn($ENV{CONSOLECOMMAND}) or die "failed to run CONSOLECOMMAND";

# This is the conserver break sequence.
$exp->send("cl0");
$exp->expect(5, "halt sent");
sleep 2;
# In case we were already in OF
$exp->send("\r\r\r\r\r");
$exp->expect(20, "ok ") or die "didn't get to OF";
print "(Sending: $ENV{OF_BOOT_COMMAND})\n";
$exp->send($ENV{OF_BOOT_COMMAND});
sleep 1;
$exp->send("\r");
$exp->expect(600, "Remapping the kernel...") or die "didn't boot";

exit;
