#!/usr/bin/expect
# Expect script to boot from syslinux.

spawn $env(CONSOLECOMMAND)
sleep 1
# Note: do not look for boot: prompt as it is not visible in bochs for some
# reason.

puts "Sending $env(BOOTCOMMAND)"
set send_slow {1 0.2}
send -s "$env(BOOTCOMMAND)\r"

set timeout 60
expect "booting the kernel"

exit
