#!/bin/sh

. /lib/partman/definitions.sh

if [ $(default_disk_label) = sun ]; then
    exit 0
fi

mypart=''
mysize=0

for dev in $DEVICES/*; do
    [ -d "$dev" ] || continue
    db_subst partman-auto/text/use_device DEVICE $(device_name $dev)
    db_metaget partman-auto/text/use_device description
    printf "$dev\t$RET\n"
done


