#!/bin/sh

set -e

. /usr/share/debconf/confmodule

if [ -f /etc/mtab ]; then
    MTAB=/etc/mtab
else
    MTAB=/proc/mounts
fi

if [ "`uname -r | grep '^2.2.'`" != "" ]; then
	rootfs=`grep '/target/ ' /etc/mtab | cut -d' ' -f 1`
else
# detect which is the root partition: /target
# ugh, I wanted to use awk, but sed has better chance of being in
# busybox
	rootfs=`/target/bin/sed -ne '/^[^ ]* \/target /s/ .*//p' $MTAB`

	rootfs=`mapdevfs $rootfs`
fi

db_subst nobootloader/confirmation ROOT "${rootfs}"
db_input high nobootloader/confirmation || true
db_go || true
