#!/bin/sh

. /lib/partman/definitions.sh

dev=$1
cd $dev

open_dialog  USES_NAMES
read_line x
close_dialog

if [ "$x" = yes ]; then
	db_metaget partman-partitioning/text/set_name description
	printf "setname\t${RET}\n"
fi
