#!/bin/sh
# This is a wrapper script that I use to build all architectures.
# It expects to have the unpacked kernel packages for various arches in
# ../alpha, etc. modules.dep files have to be put in there too.
# dpkg-cross must be installed, and so must a cross compiler, or at least
# something named alpha-linux-gcc that outputs "alpha-linux", etc.
for arch in alpha; do
	SOURCEDIR=`pwd`/../$arch dpkg-buildpackage -b -a$arch -rfakeroot -us -uc -tc
done
dpkg-buildpackage -rfakeroot -us -uc -tc
