#!/bin/sh

cd $1

num=$2
id=$3
size=$4
type=$5
fs=$6
path=$7
name=$8

if [ -f $id/bootable ]; then
    if [ "$TERM" = xterm -o "$TERM" = bterm ]; then
	printf " ↯"
    else
	printf " B"
    fi
else
    printf "  "
fi

# Local Variables:
# coding: utf-8
# End:
