#!/bin/sh

. /usr/share/debconf/confmodule

cd $1

num=$2
id=$3
size=$4
type=$5
fs=$6
path=$7
name=$8

db_metaget partman/text/free_space description

if [ "$fs" = free ]; then
    filesystem="$RET"
elif [ -f $id/acting_filesystem ]; then
    filesystem=$(cat $id/acting_filesystem)
elif [ -f $id/detected_filesystem -a ! -f $id/method ]; then
    filesystem=$(cat $id/detected_filesystem)
else
    filesystem=''
fi

printf " %-10s" "$filesystem" #TODO: language dependent length

