#!/bin/sh

cd $1

num=$2
id=$3
size=$4
type=$5
fs=$6
path=$7
name=$8

if [ -f $id/mountpoint -a -f $id/method ]; then
    mountpoint=$(cat $id/mountpoint)
else
    mountpoint=''
fi

printf " %-20s" "$mountpoint"
