#! /bin/sh
#
# Menu test script for autopartkit

# Are there any detected disks?
if [ ! -d /dev/discs ]; then
    exit 1
fi

# Is some disk already mounted
if df /target | grep -q /target  ; then
    exit 1
fi

exit 0
