#! /bin/sh -e

run_parts() {
    partsdir="$1"

    for script in "$partsdir"/*; do
	if [ -x "$script" ] ; then
	    "$script" || true
	else
	    echo "error: Unable to execute $script" 1>&2
	fi
    done
}

# Run all scripts to choose table file
run_parts /usr/lib/autopartkit.d

# Using support script to work around bug in cdebconf.
#table=`autopartkit-gettable`

if autopartkit autopartkit/partition_table ; then
    :
else
    # This should use debconf to report the error.
    echo "error: autopartkit failed."
    # No sleep in d-i environment [2002-08-21]
    #sleep 10
    exit 1
fi

##DEBHELPER##
