#!/usr/bin/perl
# Expect script to run for partially interactive first stage installs using
# the dialog frontend. At least partitioning must be preseeded.
use Expect;

# Allow running from cron.
if ($ENV{TERM} eq "" || $ENV{TERM} eq "dumb") {
        $ENV{TERM}="vt100";
}

my $exp = Expect->spawn($ENV{CONSOLECOMMAND}) or die "failed to start: $!";

#$exp->debug(2);
#$exp->exp_internal(1);
my $time_idle=0;
while (1) {
	$exp->expect($ENV{STAGE_1_MAX_INACTIVITY},
		[ timeout => sub {
			$time_idle+=$ENV{STAGE_1_MAX_INACTIVITY};
			if ($time_idle > $ENV{STAGE_1_MAX_TIME}) {
				die "install failed (timeout)";
			}
		} ],
		[ "-re", "step.*failed" => sub { exit 1 } ],
		[ "English" => sub { $time_idle=0; sleep 2; $exp->send("\r"); exp_continue_timeout } ],
		[ "-re", "<Go.*Back>" => sub { $time_idle=0; sleep 2; $exp->send("\r"); exp_continue_timeout } ],
		[ "<Continue>" => sub { $time_idle=-0; sleep 2; $exp->send("\r"); exp_continue_timeout } ],
		[ "-re", "rebooting.*the.*system." => sub { } ],
		[ "-re", "down.*NOW" => sub { } ],
		[ "-re", "Sending.*SIGTERM" => sub {} ],
	) && exit;
}
