#!/usr/bin/perl
# Expect script to install on s390 in hercules. Currently s390 cannot be
# preseeded, so this walks all the way through.
use Expect;

my $exp = Expect->spawn($ENV{CONSOLECOMMAND}) or die "failed to start: $!";
#$exp->debug(2);
##$exp->exp_internal(1);

sub question {
	my $question=shift;
	my $response=shift;

	if (! length $response) {
		$response=" "; # take default
	}
	
	$exp->expect($ENV{STAGE_1_MAX_TIME}, $question) or die "failed to find $question";
	$exp->expect(3, "Prompt: '?' for help>");
	$exp->send(".".$response."\r");
}

question("Network device type:", 1);
question("CTC device:", 1);
question("Protocol for this connection:", 1);
question("Primary network interface:", 2); # ctc0
question("IP address:", $ENV{S390_IP});
question("Point-to-point address:", $ENV{S390_PTP_IP});
question("Name server addresses:", $env{S390_NAMESERVER_IP});
question("Hostname:", "debian");
question("Domain name:", "test");
question("Remote installation password:", $ENV{ROOT_PASSWORD}); # root will do
question("Password confirmation:", $ENV{ROOT_PASSWORD});

# Could stop here and ssh in to complete the install, but since that uses
# the harder to drive newt interface, and none of the other autoinstall
# scripts for that would work since the partitioner is different and
# there's no presseding, I'll just continue using the console instead.

#TODO
#question("");

exit
