#!/usr/bin/expect
# Expect script to run for partially interactive first stage installs using the
# dialog frontend. At least partitioning must be preseeded.

spawn -noecho $env(CONSOLECOMMAND)

set timeout $env(STAGE_1_MAX_TIME)

expect {
	"English" {
		sleep 2
		send "\r"
		exp_continue -continue_timer
	} -re "<Go.*Back>" {
		sleep 2
		send "\r"
		exp_continue -continue_timer
	} -re "rebooting.*the.*system." {
		exit
	} -re "down.*NOW" {
		exit
	} -re "Sending.*SIGTERM" {
		exit
	} -re "Installation.*step.*failed" {
		exit 1
	} timeout {
		puts "timeout!"
		exit 1
	}
}

exit
