#!/usr/bin/perl
# Expect script to run for partially interactive first stage installs using
# the dialog frontend. At least partitioning must be preseeded.
use Expect;

# Allow running from cron.
if ($ENV{TERM} eq "" || $ENV{TERM} eq "dumb") {
        $ENV{TERM}="vt100";
}

my $exp = Expect->spawn($ENV{CONSOLECOMMAND}) or die "failed to start: $!";

#$exp->debug(2);
#$exp->exp_internal(1);
my $start_time=time;
while (1) {
	$exp->expect($ENV{STAGE_1_MAX_INACTIVITY},
		[ timeout => sub { die "install failed (timeout on inactivity)" } ],
		[ "-re", "step.*failed" => sub { exit 1 } ],
		[ "English" => sub { sleep 2; $exp->send("\r") } ],
		[ "-re", "<Go.*Back>" => sub { sleep 2; $exp->send("\r") } ],
		[ "<Continue>" => sub { sleep 2; $exp->send("\r") } ],
		[ "-re", "rebooting.*the.*system." => sub { exit } ],
		[ "-re", "down.*NOW" => sub { exit } ],
		[ "-re", "Sending.*SIGTERM" => sub { exit } ],
	);
	
	if (time - $start_time > $ENV{STAGE_1_MAX_TIME}) {
		die "install failed (timeout)";
	}
}
