#!/usr/bin/expect
# Expect script to handle a mostly noninteractive second stage. Assumes
# that base-config has been preseeded to not ask for anything except for
# the root password.
# 
# Note that STAGE_2_DATA_GATHER should cd to /etc if the system seems ok.
# 
# Ends up with root logged in at the prompt, assuming all went well.

spawn -noecho $env(CONSOLECOMMAND)

set timeout $env(STAGE_2_MAX_TIME)

expect {
	-re "Root.*password:" {
		send "$env(ROOT_PASSWORD)\r" ; exp_continue
	} "ogin:" {
		send "root\r" ; exp_continue -continue_timer
	} "word:" {
		send "$env(ROOT_PASSWORD)\r" ; exp_continue -continue_timer
	} ":~#" {
		send "$env(STAGE_2_DATA_GATHER); cd /etc\r" ; exp_continue
	} ":/etc#" {
		exit
	} timeout {
		puts "timeout!"
		exit 1
	}
}

exit
