#!/usr/bin/expect
# Expect script to handle a mostly noninteractive second stage. Assumes
# that base-config has been preseeded to not ask for anything except for
# the root password. Ends when the system is installed and at a login
# prompt.

spawn -noecho $env(CONSOLECOMMAND)

set timeout $env(STAGE_2_MAX_TIME)

expect {
	-re "Root.*password:" {
		sleep 1
		send "$env(ROOT_PASSWORD)\r" ; exp_continue
	} -re "password.*user:" {
		sleep 1
		send "$env(USER_PASSWORD)\r" ; exp_continue
	} "ogin:" {
		exit
	} "The Server is in Graphics Mode" {
		exit
	} timeout {
		puts "timeout!"
		exit 1
	}
}

exit
