#!/usr/bin/expect
# Expect script to handle a mostly noninteractive second stage. Assumes
# that base-config has been preseeded to not ask for anything except for
# the root password.
# 
# Note that STAGE_2_DATA_GATHER should output "Yes, looks good!"
# if the system seems ok.
# 
# Ends up with root logged in at the prompt, assuming all went well.

spawn -noecho $env(CONSOLECOMMAND)

set timeout $env(STAGE_2_MAX_TIME)

expect {
	"Root password:" {
		"$env(ROOT_PASSWORD)\r"
	} "ogin:" {
		"root\r"
	} "word:" {
		"$env(ROOT_PASSWORD)\r"
	} ":~#" {
		"$env(STAGE_2_DATA_GATHER)\r"
	} "Yes, looks good!" {
		exit
	} timeout {
		puts "timeout!"
		exit 1
	}
}

exit
