#!/usr/bin/perl
# Gathers data about an installed systen over ssh.
use Expect;

my $timeout=$ENV{STAGE_2_MAX_TIME};

my $exp = Expect->spawn("ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $ENV{USER}\@$ENV{MACHINE}");
$exp->expect($timeout, "Password:");
$exp->send("$ENV{USER_PASSWORD}\r");
$exp->expect($timeout, "Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY");
$exp->send("uname -a; mount; df -h; free; locale; dmesg; dpkg -l\r");
foreach my $log (qw{status hardware-summary syslog partman}) {
	$exp->send("cat /var/log/debian-installer/$log\r");
}
$exp->send("exit\r");
$exp->interact;
