#!/bin/sh

. /lib/partman/definitions.sh

for dev in $DEVICES/*; do
	[ -d $dev ] || continue
	cd $dev
	open_dialog PARTITIONS
	while { read_line num id size type fs path name; [ "$id" ]; }; do
	    [ $fs != free ] || continue
	    [ -f "$id/method" ] || continue
	    [ -f "$id/acting_filesystem" ] || continue
	    method=$(cat $id/method)
	    filesystem=$(cat $id/acting_filesystem)
	    case "$filesystem" in
		ext2)
		    [ -f "$id/mountpoint" ] || continue
		    mountpoint=$(cat $id/mountpoint)
		    if [ -f "$id/mountoptions" ]; then
			options=$(cat $id/mountoptions | sed 's/ //g')
		    else
			options=''
		    fi
		    if [ -z "$options" ]; then
			options=defaults
		    fi
		    if [ "$mountpoint" = / ]; then
			options="${options},errors=remount-ro"
			pass=1
		    else
			pass=2
		    fi
		    echo "$path" "$mountpoint" ext2 $options 0 $pass
		    ;;
		fat16|fat32)
		    [ -f "$id/mountpoint" ] || continue
		    mountpoint=$(cat $id/mountpoint)
		    options=''
		    if [ -f "$id/mountoptions" ]; then
			options=$(cat $id/mountoptions | sed 's/ //g')
		    fi
		    if [ -z "$options" ]; then
			options=defaults
		    fi
		    echo "$path" "$mountpoint" vfat $options 0 2
		    ;;
		linux-swap)
		    echo "$path" none swap sw 0 0
		    ;;
	    esac
	done
	close_dialog
done

