#! /bin/sh -e

. /usr/share/debconf/confmodule

#db_capb BACKUP

# Critical, as we always want the question to be asked. It's kind of
# pointless to run cdebconf-priority if you DON'T want to answer the
# question.
db_input critical debconf/priority || true
db_go

# horrible, horrible hack. The changed value of debconf/priority is
# only caught by db_set, not by db_go. I'm not quite sure what to do
# to catch it in db_go...
db_get debconf/priority || true
db_set debconf/priority "$RET" || true
