#! /bin/sh -e

. /usr/share/debconf/confmodule

# run-parts is part of debianutils, is it available in d-i? [pere 2002-11-02]
if /target/bin/run-parts --report /usr/lib/prebaseconfig.d ; then
    :
else
    echo "error: run-parts failed.  Using shell script loop instead." 1>&2
    # Using this until run-parts is available.
    for f in /usr/lib/prebaseconfig.d/*; do
        if [ -x $f ] ; then
            $f || true
        else
            echo "error: Unable to execute $f" 1>&2
        fi
    done
fi

umount -a || true

(sleep 5; /sbin/reboot) &

db_fset prebaseconfig/reboot_in_progress seen false || true
db_input critical prebaseconfig/reboot_in_progress || true
db_go || true
