#! /bin/sh -e
#

# Helper script to avoid trigging bug in the C implementation of
# cdebconf, which ignores DEBCONF_REDIR.

. /usr/share/debconf/confmodule

set -x

if db_get autopartkit/partition_table ; then
    echo "$RET"
else
    RV=$?
    echo "error: db_get autopartkit/partition_table failed" 1>&2
    exit $RV
fi
