#!/bin/sh

. /lib/partman/definitions.sh

dev=$1
id=$2
cd $dev

if [ -f $id/method ]; then
    method=$(cat $id/method)
else
    method=dont_use
fi


db_metaget partman/method_long/$method description || RET=''

if [ "$RET" ]; then
    description="$RET"
else
    description="$method"
fi
	
db_metaget partman-target/text/method description
printf "method\t%-25s%s\n" "${RET}" "$description"
