#!/bin/sh

. /usr/share/debconf/confmodule

dev=$1
id=$2

number_filesystems=$(
    for i in /lib/partman/valid_filesystems/*; do
	if [ -x $i ]; then $i $dev $id existing; fi
    done | wc -l
)

db_metaget partman-basicmethods/text/keep description

if [ "$number_filesystems" -ge 1 ]; then
    printf "keep\t${RET}\n"
fi

