.\"                                      Hey, EMACS: -*- nroff -*-
.TH DI-NETBOOT-ASSISTANT "1" "August 2009" "Frank Lin Piat" "User Commands"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.SH NAME
di-netboot-assistant \- Debian-Installer netboot assistant
.SH SYNOPSIS
\fBdi\-netboot\-assistant\fR [\fB\-hv\fR] [\fB\-\-verbose\fR] [\fB\-\-offline\fR] {[install\ \fIimage\fR...] | [uninstall\ \fIimage\fR...] | [uncache\ \fIimage\fR...] | [purge\ \fIimage\fR...] | [rebuild-menu] } [\fB\-\-arch=\fR\fB\fIarch\fR\fR] [\fB\-\-di\-args=\fR\fB\fIARGS\fR\fR] [\fB\-\-target\-args=\fR\fB\fIARGS\fR\fR] [\fB\-\-alias=\fR\fB\fIalias\fR\fR]
.SH DESCRIPTION
.PP
\fBdi\-netboot\-assistant\fR is a simple tool to download and extract latest debian installer netboot images.
.PP
Unless the
\fB\-h\fR,
\fB\-\-help\fR,
\fB\-v\fR, or
\fB\-\-version\fR
option is given, one of the commands below must be present\&.
.PP
install
.RS 4
install is followed by a repository name desired for installation\&. The repository name has to be one of those declared in \fI/etc/di-netboot-assistant/di-sources\&.list\fR. The image will be installed/extracted in the default location (declared in \fI/etc/di-netboot-assistant/di-netboot-assistant.conf\fR).
.RE
.PP
uninstall
.RS 4
uninstall is followed by the name of the repository to be uninstalled (or the repository's alias if you used \fB--alias=\fR)\&. The netboot files related to that distribution will be removed from the TFTP server.
.RE
.PP
uncache
.RS 4
uncache will clean the cached files for the given netboot image. You must specify a repository name (not an \fB--alias=\fR name).
.RE
.PP
purge
.RS 4
purge is followed by a repository name desired for installation\&. \fIpurge\fR is identical to running \fIuninstall\fR then \fIuncache\fR for a given repository.
.RE
.PP
rebuild-menu
.RS 4
rebuild-menu will rebuild the top level menu. It's only usefull if you have modified \fIdi-netboot-assistant.conf\fR and you are using some client images that have top level menu (like i386, amd64 and ia64). This command takes no argument.
.RE
.SH "OPTIONS"
.PP
\fB\-h\fR, \fB\-\-help\fR
Print this message and exit
.TP
\fB\-v\fR, \fB\-\-version\fR
Print script version and exit
.TP
\fB\-\-alias=\fR\fB\fIalias\fR\fR
Specify the alias name under wich this repository will be saved. Alias names can only contain alphanumeric, "_" and "-" characters. This is especially useful for daily images. By default, the alias name is the same as the repository name.
.TP
\fB\-\-arch=\fR\fB\fIarch\fR\fR
Specify the architecture you want to install or purge. The architecture you can use for the install action must be declared in \fI/etc/di-netboot-assistant/di-sources\&.list\fR. The architecture you can use for purge action in one of those you previously installed ! The usable architectures can be listed by leaving \fB\-\-arch=\fR empty. The default architecture is the current one (as reported by \fBdpkg \-\-dpkg --print-architecture).
.TP
\fB\-\-verbose\fR
Verbose messages
.TP
\fB\-\-di-args=\fR"\fB\fIARGS\fR\fR"
Debian-Installer boot arguments. The specified arguments will be *appended* to the one provided in the downloaded image, before the "--". (You can also define \fBDI_ARGS=\fR in \fBdi-netboot-assistant.conf\fR).
.TP
\fB\-\-target\-args=\fR"\fB\fIARGS\fR\fR"
Boot arguments for the target (installed) system. The specified arguments will be *appended* to the one provided in the downloaded image, at the very end of the line. (You can also define \fBTARGET_ARGS=\fR in \fBdi-netboot-assistant.conf\fR).
.TP
\fB\-\-offline\fR
Don't download the files (use the files cached previously).
.RE
.SH EXAMPLES

To install a netboot image for the \fIstable\fR repository, for the default architecture.
.br
\fB	di-netboot-assistant install stable\fP
.br

To list the installed netboot image that can removed.
.br
\fB	di-netboot-assistant purge\fP
.br

To remove a netboot image for the \fIstable\fR repository, for the default architecture.
.br
\fB	di-netboot-assistant purge stable\fP
.br


.
.SH FILES
.PP
\fB/etc/di-netboot-assistant/di-netboot-assistant.conf\fR
.RS 4
The default system-wide configuration file. The file syntax must be bash(1) compatible.
.RE
.PP
\fB~/.di-netboot-assistant/di-netboot-assistant.conf\fR
.RS 4
User's own configuration file. The file syntax must be bash(1) compatible. (see /usr/share/doc/di-netboot-assistant/examples/peruser.di-netboot-assistant.conf)
.RE
.PP
\fB/etc/di-netboot-assistant/di-sources.list\fR
.RS 4
This file contains the list of downloadable netboot images.
.RE
.PP
\fB/etc/di-netboot-assistant/pxelinux.HEAD\fR
.RS 4
The content of this file is prepended to the generated PXELinux config file (i.e boot menu). PXELinux bootloader is used on BIOS based i386 and amd64 systems.
.RE
.PP
\fB/etc/di-netboot-assistant/elilo.HEAD\fR
.RS 4
The content of this file is prepended to the generated Elilo config file (i.e boot menu). Elilo bootloader is used on EFI based systems like ia64 and a few i386 systems.
.RE
.PP
\fB/var/lib/di-netboot-assistant/\fR
.RS 4
The folder where hints about installed netboot images are stored. Do not edit those files, re-use \fBinstall\fR to modify the settings of installed image.
.RE
.PP
\fB/var/cache/di-netboot-assistant/\fR
.RS 4
The folder where downloaded files are stored (cached) before "installing" them. Use the action \fBuncache\fR to remove cached files.
.RE
.SH SECURITY
Do not use sudo to grant execution right to di-netboot-assistant (see the README file).
.SH PROXY
di-netboot-assistant uses wget or curl to actually download the files. You can set the environnement variables accordingly.
.SH AUTHOR
di-netboot-assistant was written by Frank Lin PIAT <fpiat@klabs.be>.
