#!/bin/sh

. /lib/partman/definitions.sh

enable_swap

for dev in $DEVICES/*; do
    [ -d "$dev" ] || continue
    cd $dev
    partitions=
    open_dialog PARTITIONS
    while { read_line num id size type fs path name; [ "$id" ]; }; do
	[ "$fs" != free ] || continue
        partitions="$partitions $id,$num"
    done
    close_dialog
    
    for part in $partitions; do
        id=${part%,*}
        num=${part#*,}
	[ -f $id/method -a -f $id/format \
	    -a -f $id/acting_filesystem ] || continue
	filesystem=$(cat $id/acting_filesystem)
	case $filesystem in
	    ext3)
		log "Try to create file system for $dev/$id"
		open_dialog PARTITION_INFO $id
		read_line x1 x2 x3 x4 x5 device x6
		close_dialog
		db_subst partman-ext3/progress_formatting TYPE "$filesystem"
		db_subst partman-ext3/progress_formatting PARTITION "$num"
		db_subst partman-ext3/progress_formatting DEVICE $(humandev $(cat device))
		status=failed
		if [ -x /sbin/tune2fs ]; then
		    name_progress_bar partman-ext3/progress_formatting
		    open_dialog CREATE_FILE_SYSTEM $id ext2
		    read_line status
		    close_dialog
		    sync
		    if [ "$status" = OK ]; then
			/sbin/tune2fs -j $device >/dev/null 2>>/var/log/messages || status=failed
			sync
		    fi
		fi
		if [ "$status" != OK ]; then
		    db_progress START 0 3 partman/text/please_wait
		    db_progress INFO partman-ext3/progress_formatting
		    db_progress SET 1
		    if
			mkfs.ext3 $device >/dev/null 2>>/var/log/messages
		    then
			sync
			status=OK
		    else
			status=failed
		    fi
		    db_progress STOP
		fi
                if [ "$status" != OK ]; then
		    db_fset partman-ext3/create_failed seen false
		    db_subst partman-ext3/create_failed PARTITION "$num"
		    db_subst partman-ext3/create_failed DEVICE $(humandev $(cat device))
		    db_input critical partman-ext3/create_failed || true
		    db_go || true
		    disable_swap
		    exit 1
		fi
		;;
	esac
    done
done

disable_swap
