.TH pcidetect 1

.SH NAME
pcidetect \- Determine the kernel modules required to support your hardware.

.SH DESCRIPTION
.PP
\fIpcidetect\fP use libpci to discover your local hardware, it then uses an internal table to determine the correct kernel module to support the device.

.PP
It currently only supports network devices

.SH SEE ALSO
lspci

.SH BUGS
Unknown so far, but im sure there are some lurking in there somewhere.

.SH AUTHOR
Glenn McGrath <bug1@optushome.com.au>

