#!/bin/sh

. /lib/partman/definitions.sh

dev=$1
id=$2

cd $dev

valid_boot=no
open_dialog VALID_FLAGS $id
while { read_line flag; [ "$flag" ]; }; do
    if [ "$flag" = boot ]; then
	valid_boot=yes
    fi
done
close_dialog

[ $valid_boot = yes ] || exit 0

bootable=no
open_dialog GET_FLAGS $id
while { read_line flag; [ "$flag" ]; }; do
    if [ "$flag" = boot ]; then
	bootable=yes
    fi
done
close_dialog

if [ $bootable = yes ]; then
    db_metaget partman-partitioning/text/bootable_off description
    printf "unbootable\t${RET}\n"
else
    db_metaget partman-partitioning/text/bootable_on description
    printf "bootable\t${RET}\n"
fi

