#!/bin/sh

dev=$1
id=$2
method=$3

case $method in
    formatable)
	echo ext2
	;;
    existing)
	[ -f $id/detected_filesystem ] || exit 0
	fs=$(cat $id/detected_filesystem)
	
	case "$fs" in
	    ext2)
		echo ext2
		;;
	esac
	;;
esac


