#!/bin/sh

. /lib/partman/definitions.sh

dev=$1
id=$2
method=$3

db_metaget partman-basicfilesystems/text/swap description

case $method in
    formatable)
	printf "linux-swap\t${RET}\n"
	;;
    existing)
	[ -f $id/detected_filesystem ] || exit 0
	fs=$(cat $id/detected_filesystem)
	
	case "$fs" in
	    linux-swap)
		printf "linux-swap\t${RET}\n"
		;;
	esac
	;;
esac


