#!/bin/sh -e

SUITE=main
if test "$3" != ""; then
    SUITE="$3"
fi
if test "$1" = "Packages"
then
    # Don't quote this line, it needs to expand the star!
    file=dists/sid/$SUITE/debian-installer/binary-*/Packages
else
    file="$1"
fi
ln -sf /cdrom/$file "$2"
