#!/bin/sh
set -e

MACHINE="$1"
export MACHINE
SCHEME="$2"
export SCHEME

started=""
inheader=""

divider () {
	echo "============================================================================"
}
	
header () {
	if [ -z "$inheader" ]; then
		inheader=1
		divider
		LANG=C echo "Date: $(date)"
		echo "$@"
	fi
}

endheader () {
	if [ "$inheader" ]; then
		inheader=
		divider
	fi
}

error () {
	if [ "$started" ]; then
		echo
		header "Unsuccessful finish: $SCHEME"
		echo "$@"
		endheader
	else
		echo "$@" >&2
	fi
	
	exit 1
}

config () {
	var="$1"
	shift 1
#	echo "$var=\"$@\""
	eval "export $var='$@'"
}

use () {
	. $DI_TESTDIR/schemes/$MACHINE/$1
}

export DIGRESSDIR=$(dirname $0)

if [ -z "$DI_TESTDIR" ] || [ ! -e "$DI_TESTDIR/config" ]; then
	export DI_TESTDIR=$DIGRESSDIR
	if [ -z "$DI_TESTDIR" ] || [ ! -e "$DI_TESTDIR/config" ]; then
		error "Cannot determine DI_TESTDIR"
	fi
fi

PATH=$PATH:$DIGRESSDIR/boot:$DIGRESSDIR/preboot:$DIGRESSDIR/console:$DIGRESSDIR/test_1:$DIGRESSDIR/test_2
export PATH

if [ -z "$SCHEME" ]; then
	SCHEME=d-i
fi

if [ -z "$MACHINE" ]; then
	error "Usage: test-harness machine [scheme]"
fi

if [ ! -e "$DI_TESTDIR/schemes/$MACHINE" ]; then
	error "Unknown machine $MACHINE"
fi

. $DI_TESTDIR/config
use common
use $SCHEME

started=1
header "Booting: $MACHINE"
echo "Scheme: $SCHEME -- $DESCRIPTION"

if [ "$PREBOOT" ]; then
	echo "Setting up..."
	for p in $PREBOOT; do
		if ! $p; then
			error "PREBOOT $p failed"
		fi
	done
fi
	
endheader
if ! $BOOT; then
	error "BOOT $BOOT failed"
fi

if [ -n "$TEST_1" ]; then
	echo
	header "Testing the first stage install..."
	endheader
	for t in $TEST_1; do
		if ! $t; then
			error "TEST_1 $t failed"
		fi
	done
fi

if [ -n "$TEST_2" ]; then
	echo
	header "Testing the second stage install..."
	endheader
	for t in $TEST_2; do
		if ! $t; then
			error "TEST_2 $t failed"
		fi
	done
fi

echo
header "Successful finish: $SCHEME"
endheader
exit 0

