#!/bin/sh
. /usr/share/debconf/confmodule
db_title "Low memory"
db_input critical debian-installer/lowmem || true
db_go || true
	
db_set debian-installer/framebuffer false

db_set languagechooser/language-name "English (other)"
db_fset languagechooser/language-name seen true
