#!/bin/sh
# Cleanup after the first /linuxrc, which left the initrd mounted
# on /initrd.
umount /initrd/dev
umount /initrd
freeramdisk /dev/rd/0

for script in /etc/rcS.d/S[0-9][0-9]*; do
    . $script
done
