#!/bin/sh
echo 'Setting up Userspace DevFS: '
# run update-dev once, just to make sure /dev/discs is set up correctly.
echo 'done'
echo -n ' Hard disk and partitions... '
/usr/bin/update-dev
echo 'done'
