#!/bin/sh
echo 'Setting up Userspace DevFS: '
echo -n 'mounting /proc... '
mount /proc
# run update-dev once, just to make sure /dev/discs is set up correctly.
echo -n ' Hard disk and partitions... '
/usr/bin/update-dev
echo 'done'
