#!/bin/sh

. /lib/partman/definitions.sh

dev=$1
num=$2
id=$3
size=$4
type=$5
fs=$6
path=$7
name=$8

cd $dev

[ -d $id ] || mkdir $id

if [ $fs = free -a -f $id/method ]; then
    rm $id/method
fi

if [ ! -f $id/method ]; then
    [ ! -f $id/acting_filesystem ] || rm $id/acting_filesystem
    >$id/available_filesystems
    exit 0
fi

method=$(cat $id/method)

if [ -f $id/format ]; then
    property=formatable
else
    property=existing
fi

# sed can be removed here
filesystems=$(
    for i in /lib/partman/valid_filesystems/*; do
	if [ -x $i ]; then $i $dev $id "$property"; fi
    done | sed "s/${TAB}.*//"
)

available=''
for fs in $filesystems; do
    if [ "$fs" ]; then
	db_metaget partman/filesystem_long/$fs description || RET=''
	RET=${RET:-$fs}
	if [ "$available" ]; then
	    available="${available}${NL}${fs}${TAB}${RET}"
	else
	    available="${fs}${TAB}${RET}"
	fi
    fi
done

echo "$available" >$dev/$id/available_filesystems

if [ -f $id/acting_filesystem ]; then
    old_acting=$(cat $id/acting_filesystem)
else
    old_acting=''
fi

# The outer echo removes the spaces
case $(echo $(echo "$available" | wc -l)) in
    0)
	if [ -f $id/acting_filesystem ]; then
	    rm $id/acting_filesystem
	fi
	;;
    1)
	echo ${available%$TAB*} >$id/acting_filesystem
	;;
    *)
	if [ -f $id/filesystem ]; then
	    cp $id/filesystem $id/acting_filesystem
	else
	    if [ -f $id/acting_filesystem ]; then
		rm $id/acting_filesystem
	    fi
	fi
	;;
esac

if
    [ -f $dev/$id/acting_filesystem ] \
	&& new_acting=$(cat $dev/$id/acting_filesystem) \
	&& [ "$old_acting" != "$new_acting" ] \
	&& [ -f /lib/partman/parted_names/$new_acting ]
then
    parted_name=$(cat /lib/partman/parted_names/$new_acting)
    open_dialog CHANGE_FILE_SYSTEM $id $parted_name
    close_dialog
fi

