#!/bin/sh

rm -f $DI_TESTDIR/state/hercules-$MACHINE-$SCHEME.*

PIDFILE=$DI_TESTDIR/state/hercules-$MACHINE-$SCHEME.pid
# Stop hercules.
if [ ! -e $PIDFILE ]; then
	echo "No pid file $PIDFILE" >&2
	exit 0
else
	pid=$(cat $PIDFILE)
	if ! pidof hercules | grep -q $pid; then
		echo "stale pid" >&2
	else
		kill -9 $pid
	fi
	echo "Stopped hercules (pid $pid)"
fi
