#!/bin/sh
PIDFILE=$DI_TESTDIR/state/bochs-$MACHINE-$SCHEME.pid
# Stop bochs.
if [ ! -e $PIDFILE ]; then
	echo "No pid file $PIDFILE" >&2
	exit 1
fi
pid=$(cat $PIDFILE)
if ! pidof bochs-bin | grep -q $pid; then
	echo "stale pid" >&2
else
	kill -9 $pid
fi
echo "Stopped bochs (pid $pid)"
rm -f $DI_TESTDIR/state/bochs-$MACHINE-$SCHEME.*
