#!/bin/sh

exit 0

PIDFILE=$DI_TESTDIR/state/hercules-$MACHINE-$SCHEME.pid
# Stop hercules.
if [ ! -e $PIDFILE ]; then
	echo "No pid file $PIDFILE" >&2
	exit 1
fi
pid=$(cat $PIDFILE)
if ! pidof hercules | grep -q $pid; then
	echo "stale pid" >&2
else
	kill -9 $pid
fi
echo "Stopped hercules (pid $pid)"
rm -f $DI_TESTDIR/state/hercules-$MACHINE-$SCHEME.*
