#!/bin/sh
PIDFILE=$STATE_DIR/qemu-$MACHINE-$SCHEME.pid
# Stop qemu.
if [ ! -e $PIDFILE ]; then
	echo "No pid file $PIDFILE" >&2
	exit 1
fi
pid=$(cat $PIDFILE)
if ! pidof qemu | grep -q $pid; then
	echo "stale pid" >&2
else
	kill -9 $pid
	echo "Stopped qemu (pid $pid)"
fi
