#!/bin/sh
PIDFILE=$STATE_DIR/qemu-$MACHINE-$SCHEME.pid

# Signal qemu control process to save state.
if [ -e $STATE_DIR/qemu-$MACHINE-$SCHEME.control.pid ]; then
	kill -USR1 $(cat $STATE_DIR/qemu-$MACHINE-$SCHEME.control.pid) || true
	# wait for it to finish saving
	# TODO racey
	sleep 60
fi

# Stop qemu.
if [ ! -e $PIDFILE ]; then
	echo "No pid file $PIDFILE" >&2
	exit 1
fi
pid=$(cat $PIDFILE)
if [ -z "$QEMU_COMMAND" ]; then
	QEMU_COMMAND=qemu
fi
if ! pidof $QEMU_COMMAND | grep -q $pid; then
	echo "stale pid" >&2
else
	kill -9 $pid
	echo "Stopped qemu (pid $pid)"
fi

# wait for sockets to close etc
sleep 60
