#!/bin/sh -e

. /usr/share/debconf/confmodule

localecode="debian-installer/locale"
# We need to remember which locale has been set in languagechooser
# as countrychooser will also be able to change debian-installer/locale
languagechooserlocalecode="languagechooser/locale"
languagecode="debian-installer/language"
countrycode="debian-installer/country"

log() {
    logger -t languagechooser "info: $@"
}

#   debconf/language is an alias for debian-installer/language
db_register "$languagecode" "debconf/language"

# Only display the translated texts (ie the English "translation")
# when in UTF-8 mode.
if ( echo $LANG $LC_CTYPE | grep -q UTF-8 ); then
  db_set debconf/language en
else
  db_set debconf/language C
fi

db_fset "languagechooser/language-name" seen false
db_fset "$languagecode" seen false
db_input critical "languagechooser/language-name" || [ $? -eq 30 ]
if db_go; then
    db_get "languagechooser/language-name"
    if test "$RET" ; then
	LANGNAME="$RET"
	. languagemap
	db_set "$languagecode" "$LANGUAGELIST"
	db_set "$localecode"   "$LOCALE"
	# For "remembering" which locale is set by languagechooser
	# this is supposed to ba a *valid* locale
	db_set "$languagechooserlocalecode"   "$LOCALE"
	db_set "$countrycode"  "$COUNTRY"
    else
	# Error, not sure how to handle it
	:
    fi
else
    # Error, not sure how to handle it
    :
fi

db_get "$languagecode"
db_set "debconf/language" "$LANGUAGELIST"

case "$LANGUAGE" in
    ar|bg|el|he|ja|ko|tr|uk|ru|zh)
	anna-install bterm-unifont
	;;
esac

log "$localecode   = '$LOCALE'"
log "$languagechooserlocalecode   = '$LOCALE'"
log "$languagecode = '$LANGUAGELIST'"
log "$countrycode  = '$COUNTRY'"

exit 0
