#!/bin/sh
# 
# A script to find out which .po files has been updated since the last
# update, according to the PO-Revision flag and the Debian changelog
# 
# Copyright (c) 2004 Nikolai Prokoschenko (nikolai@prokoschenko.de)
#
# This script is available under the GNU Public License
# (http://www.gnu.org/licenses/gpl.txt) 

if [ "x$1" = "x" ]
then
  echo "Usage: $0 <package-directory>"
  exit
fi

P=$1;
PACKAGE=`echo $P | sed 's/\/$//g'` 

if [ ! -d $PACKAGE ]
then
  echo "Cannot access the directory $PACKAGE!"
  exit
fi


CHANGELOG="$PACKAGE/debian/changelog"
POS="$PACKAGE/debian/po"
RELEASE="unstable"

if [ ! -e $CHANGELOG ]
then
  echo "Cannot find the changelog file!"
  exit
fi

# Line number of the changelog's old date
LINE=`grep "; urgency=" "$CHANGELOG" | grep -n "$RELEASE" | head -n 1 | sed 's/:.*//g'`

# Date of the last release
DATE=`grep "^ --" "$CHANGELOG" | head -n $LINE | tail -n 1 | sed 's/.*>  //g'`
OLD_DATE=`date -d "$DATE" +%s`

echo "* Updated translations: "

for i in $POS/*.po
do
  if [ -e $i ]
  then
    DATE=`grep PO-Revision "$i" | cut -d ":" -f 2,3 | sed 's/^ //g' | cut -d '\' -f 1`
    if date --date "$DATE" 2>/dev/null 1>&2 
    then
	NEW_DATE=`date -d "$DATE" +%s`
	if [ $NEW_DATE -gt $OLD_DATE ]
	then
# Here some magic to extract the appropriate language from
# languagechooser's 'languagelist'. $CSN is for Country Short Name and
# means the iso code of the country (i.e. CSN = "ru")
#
# grep ";$CSN;" languagelist | grep -v "^#" | head -n 1 | cut -d ";" -f 1 | sed 's/(.*)//g' | sed 's/\ *$//g'
#
# It is not used here, as the script might be universal and thus there'd
# be no languagelist available -- nevertheless, it could be a nice idea
# to include it somewhere in the Debian distribution
#
# Here another one, to extract all languages from the languagelist
#
# grep -v "^#" languagelist | while read line ; do CSN=`echo $line | cut -d ";" -f 3`; COUNTRY=`echo $line | cut -d ";" -f 1 | sed 's/(.*)//g' | sed 's/\ *$//g'`; echo $CSN $COUNTRY; done | sort | uniq
# 		
	    CSN=`basename $i | sed 's/\.po//g'`;
	    case $CSN in

	    "ar") R="Arabic";;
	    "bg") R="Bulgarian";;
	    "bs") R="Bosnian";;
	    "ca") R="Catalan";;
	    "cs") R="Czech";;
	    "da") R="Danish";;
	    "de") R="German";;
	    "el") R="Greek";;
	    "en") R="English";;
	    "es") R="Spanish";;
	    "fi") R="Finnish";;
	    "fr") R="French";;
	    "ga") R="Irish";;
	    "he") R="Hebrew";;
	    "hu") R="Hungarian";;
	    "it") R="Italian";;
	    "ja") R="Japanese";;
	    "ko") R="Korean";;
	    "lt") R="Lithuanian";;
	    "lv") R="Latvian";;
	    "nb") R="Norwegian";;
	    "nl") R="Dutch";;
	    "nn") R="Norwegian";;
	    "pl") R="Polish";;
	    "pt") R="Portuguese";;
	    "pt_BR") R="Portuguese (Brazil)";;
	    "ru") R="Russian";;
	    "sk") R="Slovak";;
	    "sl") R="Slovenian";;
	    "sq") R="Albanian";;
	    "sv") R="Swedish";;
	    "tr") R="Turkish";;
	    "uk") R="Ukrainian";;
	    "zh_CN") R="Simplified Chinese";;
	    *) R=$CSN;;
	    esac

	    # Get the translator's name

	    translator=`grep "Last-Translator" $i| sed 's/\"//g' | sed 's/Last-Translator: //g' |sed 's/<.*$//g'`		
	    
	    # Convert to UTF-8 -- the changelogs should be UTF-8, the
	    # translations need not.

	    encoding=`grep "charset=" $i | sed 's/\"//g' | sed 's/^.*charset=//g' | sed 's/n//g'`
	    trans=`echo $translator | iconv -f $encoding -t utf-8`
	    
	    # And output the changelog line
	    
	    echo "   - $R ($CSN.po) by $trans"
        fi
    fi
  fi
done
