#!/usr/bin/perl
# This program downloads summary log files for the daily image builds, and
# constructs a web page overview of the d-i builds. If you run a daily
# build, add the info for your build to the list. 
#
# The url field points to the url your build can be downloaded from, the
# email address is a contact address, the description is a breif
# description of the build. The logurl points to wherever log files are.
# The logext is an extention that is appended to the log filename.
#
# In the log directory you should have a summary$logext file, that contains
# lines in the following format:
#    arch (date) user@host ident status
#    
# Where ident describes what is being built, arch is the architecture that
# it is being built for, date is the output of the date command at the end
# of the build (in the C locale), user@host is who did the build, and
# status describes how it went (usually "success" or "failed"). A log file
# for the build should in in the file named ident$logext in the log directory.
#
# Example:
# i386 (Thu Apr 22 21:08:03 EDT 2004) joey@kite build_floppy_boot success
# i386 (Thu Apr 22 21:08:33 EDT 2004) joey@kite build_floppy_speakup success
# i386 (Thu Apr 22 21:09:29 EDT 2004) joey@kite build_floppy_root success

my @buildlist = (
	{
		url => 'http://people.debian.org/~jbailey/d-i/alpha/daily/',
		logurl => 'http://people.debian.org/~jbailey/d-i/alpha/daily/',
		email => 'jbailey@debian.org',
		description => 'daily alpha images build',
		logext => ".log",
		frequency => 1,
	},

	{
		url => 'http://debian-amd64.alioth.debian.org/debian-installer/daily/',
		logurl => 'http://debian-amd64.alioth.debian.org/debian-installer/daily/',
		email => 'Q@ping.be',
		description => 'daily amd64 images build',
		logext => ".log",
		frequency => 1,
	},
	
	{
		url => 'http://people.debian.org/~vince/d-i/images/daily/',
		logurl => 'http://people.debian.org/~vince/d-i/images/daily/',
		email => 'vince@debian.org',
		description => 'daily arm images build',
		logext => ".log",
		frequency => 1,
	},
	
	{
		url => 'http://people.debian.org/~jbailey/d-i/hppa/daily/',
		logurl => 'http://people.debian.org/~jbailey/d-i/hppa/daily/',
		email => 'jbailey@debian.org',
		description => 'daily hppa images build',
		logext => ".log",
		frequency => 1,
	},
	
	{
		url => 'http://people.debian.org/~joeyh/d-i/images/daily/',
		logurl => 'http://people.debian.org/~joeyh/d-i/images/daily/',
		email => 'joeyh@debian.org',
		description => 'daily i386 images build',
		logext => ".log",
		frequency => 1,
	},
	
	{
		url => 'http://people.debian.org/~jbailey/d-i/ia64/daily/',
		logurl => 'http://people.debian.org/~jbailey/d-i/ia64/daily/',
		email => 'jbailey@debian.org',
		description => 'daily ia64 images build',
		logext => ".log",
		frequency => 1,
	},

	{
		url => 'http://people.debian.org/~smarenka/d-i/images-m68k/daily/',
		logurl => 'http://people.debian.org/~smarenka/d-i/images-m68k/daily/',
		email => 'smarenka@debian.org',
		description => 'daily m68k images build',
		logext => ".log",
		frequency => 1,
	},

	{
		url => 'http://people.debian.org/~tbm/d-i/images/mips/daily/',
		logurl => 'http://people.debian.org/~tbm/d-i/images/mips/daily/',
		email => 'tbm@debian.org',
		description => 'daily mips images build',
		logext => ".log",
		frequency => 1,
	},

	{
		url => 'http://people.debian.org/~tbm/d-i/images/mipsel/daily/',
		logurl => 'http://people.debian.org/~tbm/d-i/images/mipsel/daily/',
		email => 'tbm@debian.org',
		description => 'daily mipsel images build',
		logext => ".log",
		frequency => 1,
	},

	{
		url => 'http://people.debian.org/~luther/d-i/images/daily/',
		logurl => 'http://people.debian.org/~luther/d-i/images/daily/',
		email => 'luther@debian.org',
		description => 'daily powerpc images build',
		logext => ".log",
		frequency => 1,
	},

	{
		url => 'http://raptor.debian.org/d-i/images/daily/',
		logurl => 'http://raptor.debian.org/d-i/images/daily/',
		email => 'waldi@debian.org',
		description => 'daily s390 images build',
		logext => ".log",
		frequency => 1,
	},

	{
		url => 'http://people.debian.org/~joshk/d-i/images/daily/',
		logurl => 'http://people.debian.org/~joshk/d-i/images/daily/',
		email => 'joshk@debian.org',
		description => 'daily sparc images build',
		logext => ".log",
		frequency => 1,
	},

	{
		url => 'http://cdimage.debian.org/pub/cdimage-testing/',
		logurl => 'http://gluck.debian.org/cdimage/log/',
		email => 'manty@debian.org',
		description => 'CD image builds',
		logext => "",
		frequency => 7, # some build only weekly
	},

#	{
#		url => 'http://somehost/',
#		logurl => 'http://somehost/',
#		email => 'you@debian.org',
#		description => 'put something informative here',
#		logext => ".log",
#		frequency => 1,
#	},
);

use warnings;
use strict;
require "aggregator.pl";

print <<EOS;
<html>
<head>
<title>debian-installer build overview</title>
</head>
<body>
<ul>
EOS

aggregate(@buildlist);

my $date=`LANG=C TZ=GMT date`;
chomp $date;
print <<"EOS"
</ul>

See also: <a href="http://buildd.debian.org/build.php?arch=&pkg=debian-installer">d-i autobuild logs</a>
and <a href="http://people.debian.org/~igloo/status.php?packages=debian-installer">d-i buildd status</a>

<hr>
$date
</body>
</html>
EOS
