#!/bin/sh

`dirname $0`/l10n/output-l10n-changes -d . 2> /dev/null > /tmp/l10n-changes

if [ "$(cat /tmp/l10n-changes)" = "Cannot find the PO directory!" ]; then
	> /tmp/l10n-changes
fi

while read line; do
	if [ "$line" = "[ Updated translations ]" ]; then
		continue
	fi

	log=`echo "$line" | cut -c 3-`

	DEBFULLNAME="Updated translations" dch -t --release-heuristic changelog "$log"
done < /tmp/l10n-changes

dch -r ""

debuild && debsign && debcommit --release && debrelease