#!/bin/sh
# Generates a list of all modules included in any of the d-i kernel udebs.
# The parameter is the directory that contains the source for kernel-wedge
# and all the packages. This is to be used in discover-data reduction.
(
	for dir in $1/*; do
		for file in $(find $dir/modules -type f | grep -v .svn | grep -v .lnk); do
			cat $file | sed 's/^-//' | grep -v \# | grep -v '^$' | sed 's!.*/!!' | sed 's/\..*//'
		done
	done
) | sort | uniq
