#!/bin/sh
set -e

runshow () {
	echo "$@"
	eval "$@"
}

config_git_anon () {
	# rewrite urls to use git://
	runshow git config --global 'url.git://git.debian.org/d-i/.insteadOf' 'git+ssh://git.debian.org/git/d-i/'
}

config_git_auth () {
	config_git_anon # speeds up checkouts
	# use ssh for pushes
	runshow git config --global 'url.git+ssh://git.debian.org/git/d-i/.pushInsteadOf' 'git+ssh://git.debian.org/git/d-i/'
}

URL=$(LANG=C git remote -v | cut -f2)
case "$URL" in
	git@*)
		config_git_auth
	;;
	http:*|https:*)
		config_git_anon
	;;
	*)
		echo "unknown svn url: $URL" >&2
		exit 1
	;;
esac

echo ""
echo "Your git is now configured to checkout d-i optimally."
echo "Now run 'mr -p checkout'"

