#!/bin/bash

# Script searches for components with pending changes (UNRELEASED) and
# either lists them or displays the relevant changelog entry.

# Usage: list-unreleased [-c]
#        -c display pending changes

# Copyright: Frans Pop <elendil@planet.nl>, 2007
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the Free
# Software Foundation; either version 2 of the License, or (at your option)
# any later version.

get_list() {
	for dir in $(find . -type d); do
		changelog="$dir/debian/changelog"
		if [ -f $changelog ] ; then
			if head -n1 $changelog | grep -q UNRELEASED; then
				echo $dir | sed "s:^\./::"
			fi
		fi
	done | sort
}

if [ "$1" = -c ]; then
	for component in $(get_list); do
		sed -n "1,/^ --/p" ./$component/debian/changelog
		echo; echo
	done
else
	echo "$(get_list)"
fi
