#!/usr/bin/perl
# This program downloads summary log files for the automatic d-i install
# tests, and constructs a web page overview. If you run an automatic test,
# add the info for your build to the list. 
#
# The url field points to the url info about your test can be downloaded
# from, the email address is a contact address, the description is a breif
# description of the test. The logurl points to wherever log files are.
# The logext is an extention that is appended to the log filename.
#
# In the log directory you should have a summary$logext file, that contains
# lines in the following format:
#    arch (date) user@host ident status [notes]
#    
# Where ident describes the test, arch is the architecture that is being 
# tested, date is the output of the date command at the end of the test
# (in the C locale), user@host is who did the test, and status describes
# how it went (usually "success" or "failed"). A log file for the test
# should in in the file named ident$logext in the log directory.
#
# Example:
# i386 (Thu Apr 22 21:08:03 EDT 2004) joey@home elephant-d-i success

my @buildlist = (
	{
		url => 'http://home.kitenet.net/~joey/d-i/logs/i386/',
		logurl => 'http://home.kitenet.net/~joey/d-i/logs/i386/',
		email => 'joeyh@debian.org',
		description => 'Joey\'s daily i386 tests',
		logext => ".log",
		frequency => 1,
	},
	{
		url => 'http://home.kitenet.net/~joey/d-i/logs/ia64/',
		logurl => 'http://home.kitenet.net/~joey/d-i/logs/ia64/',
		email => 'joeyh@debian.org',
		description => 'Joey\'s daily ia64 tests',
		logext => ".log",
		frequency => 1,
	},
	{
		url => 'http://home.kitenet.net/~joey/d-i/logs/sparc/',
		logurl => 'http://home.kitenet.net/~joey/d-i/logs/sparc/',
		email => 'joeyh@debian.org',
		description => 'Joey\'s daily sparc tests',
		logext => ".log",
		frequency => 1,
	},
	{
		url => 'http://home.kitenet.net/~joey/d-i/logs/s390/',
		logurl => 'http://home.kitenet.net/~joey/d-i/logs/s390/',
		email => 'joeyh@debian.org',
		description => 'Joey\'s daily s390 tests',
		logext => ".log",
		frequency => 1,
	},

#	{
#		url => 'http://somehost/',
#		logurl => 'http://somehost/',
#		email => 'you@debian.org',
#		description => 'put something informative here',
#		logext => ".log",
#		frequency => 1,
#	},
);

use warnings;
use strict;
require "aggregator.pl";

print <<EOS;
<html>
<head>
<title>debian-installer test overview</title>
</head>
<body>
<ul>
EOS

aggregate(@buildlist);

my $date=`LANG=C TZ=GMT date`;
chomp $date;
print <<"EOS"
</ul>

<hr>
$date
</body>
</html>
EOS
