#!/bin/sh
#
# - Search all packages needing translations under the current directory
# - Add or update these with tranlations originated from a reference file
#
#
# WORK IN PROGRESS. You have been warned!

usage () {
  echo Usage $O reference_file language_code
  exit 1
} 

if [ ! -r $1 ]
then
  echo $1: unable to read file
  exit 1
fi

if [ -z $2 ]
then
  usage
fi

# Search all packages needing translations
filelist=`find . -name templates.pot | grep "debian/po"`

# For each language, build the general PO file
for i in $filelist ; do
  newfile=`dirname $i`/$2.po
  # If a file already exists, we update it with the new translations issued
  # from the general file
  #
  # If it does does exist we simply update it
  if [ ! -f $newfile ] ; then
    # Merge reference file and templates.pot, remove obsolete entries
    # (which are irrelevant strings from other packages in the reference
    #  file)
    # and make this new file the translations file
    msgmerge $1 $i | msgattrib --no-obsolete - >$newfile
  else
    # Merge reference file and templates.pot, remove obsolete entries
    # (which are irrelevant strings from other packages in the reference
    #  file)
    msgmerge $1 $newfile | msgattrib --no-obsolete - >$newfile.new
    po_stat $newfile.new
    # Then merge this with the templates.pot file
    msgmerge -U $newfile.new $i
    po_stat $newfile.new
    mv $newfile.new $newfile
    po_stat $newfile
  fi
done




