#! /bin/sh
# This script is called at system startup
# This is where the installer actually interacts with the user

#export DEBCONF_FRONTEND=text
#export DEBCONF_DEBUG=5 

# Turn off console blanking.
echo "\033[9;0]"

/usr/bin/debconf-loadtemplate debian /var/lib/dpkg/info/*.templates 

# init will restart this script when it exits.  This will let us pick another
# frontend every time main-menu exits
if [ -z "$DEBIAN_FRONTEND" ] ; then
    for frontend in gtk slang text ; do
        if [ -e "/usr/lib/cdebconf/frontend/$frontend.so" ] ; then
            DEBIAN_FRONTEND=$frontend
            export DEBIAN_FRONTEND
            break
        fi
    done
fi

/usr/share/debconf/frontend /usr/bin/main-menu
