#! /bin/sh
# This script is called at system startup
# This is where the installer actually interacts with the user

#export DEBIAN_FRONTEND=text
#export DEBCONF_DEBUG=5 

# Turn off console blanking.
echo -n "\033[9;0]"

/usr/bin/debconf-loadtemplate debian /var/lib/dpkg/info/*.templates 

# Enable UTF-8 locale if it is available
if [ -d /usr/lib/locale/C@utf-8 ] ; then
    LANG=C@utf-8
    export LANG
    if [ linux = "$TERM" ] ; then # We are using a Linux console.
        echo -n "\033%G" # Enable UTF-8 console ("<ESC>%@" will turn it off).
        # Workaround for border strange lines in UTF-8 mode
        TERM=xterm
        export TERM
    fi
fi

# init will restart this script when it exits.  This will let us pick another
# frontend every time main-menu exits
if [ -z "$DEBIAN_FRONTEND" ] ; then
    for frontend in gtk newt slang text ; do
        if [ -e "/usr/lib/cdebconf/frontend/$frontend.so" ] ; then
            DEBIAN_FRONTEND=$frontend
            export DEBIAN_FRONTEND
            break
        fi
    done
fi

/sbin/di-main-menu
