#! /bin/sh
# This script is called at system startup
# This is where the installer actually interacts with the user

#export DEBCONF_FRONTEND=text
#export DEBCONF_DEBUG=5 

# Turn off console blanking.
echo "\033[9;0]"

/usr/bin/debconf-loadtemplate debian /var/lib/dpkg/info/*.templates 

# The loop make it possible to change frontend by installing a new frontend,
# and forcing main-menu to exit.  Not sure if it is the best way, but it
# should work.
while true do ; do

    if [ -z "$DEBIAN_FRONTEND" ] ; then
	for frontend in gtk slang text ; do
	    if [ -e "/usr/lib/cdebconf/frontend/$frontend.so" ] ; then
		DEBIAN_FRONTEND=$frontend
		export DEBIAN_FRONTEND
		break
	    fi
	done
    fi

    /usr/share/debconf/frontend /usr/bin/main-menu

    unset DEBIAN_FRONTEND
done
