#!/bin/sh
#
# Load one of vesafb and vga16fb to enable framebuffer, create
# compatibility symlinks.

if (modprobe vesafb || modprobe vga16fb) && fbset ; then
    # Add compatibility symlinks.  This hack is a workaround for bug #182176.
    test -e /dev/fb0 || ln -s /dev/fb/0 /dev/fb0
    test -e /dev/tty0 || ln -s /dev/vc/0 /dev/tty0

    test -e /dev/ptyp0 || ln -s /dev/pty/m0 /dev/ptyp0
    test -e /dev/ptyp1 || ln -s /dev/pty/m1 /dev/ptyp1
    test -e /dev/ptyp2 || ln -s /dev/pty/m2 /dev/ptyp2
    test -e /dev/ptyp3 || ln -s /dev/pty/m3 /dev/ptyp3
    test -e /dev/ptyp4 || ln -s /dev/pty/m4 /dev/ptyp4
    test -e /dev/ptyp5 || ln -s /dev/pty/m5 /dev/ptyp5
    test -e /dev/ptyp6 || ln -s /dev/pty/m6 /dev/ptyp6
    test -e /dev/ptyp7 || ln -s /dev/pty/m7 /dev/ptyp7
    test -e /dev/ptyp8 || ln -s /dev/pty/m8 /dev/ptyp8
    test -e /dev/ptyp9 || ln -s /dev/pty/m9 /dev/ptyp9
    test -e /dev/ptypa || ln -s /dev/pty/m10 /dev/ptypa
    test -e /dev/ptypb || ln -s /dev/pty/m11 /dev/ptypb
    test -e /dev/ptypc || ln -s /dev/pty/m12 /dev/ptypc
    test -e /dev/ptypd || ln -s /dev/pty/m13 /dev/ptypd
    test -e /dev/ptype || ln -s /dev/pty/m14 /dev/ptype
    test -e /dev/ptypf || ln -s /dev/pty/m15 /dev/ptypf

    test -e /dev/ttyp0 || ln -s /dev/pty/s0 /dev/ttyp0
    test -e /dev/ttyp1 || ln -s /dev/pty/s1 /dev/ttyp1
    test -e /dev/ttyp2 || ln -s /dev/pty/s2 /dev/ttyp2
    test -e /dev/ttyp3 || ln -s /dev/pty/s3 /dev/ttyp3
    test -e /dev/ttyp4 || ln -s /dev/pty/s4 /dev/ttyp4
    test -e /dev/ttyp5 || ln -s /dev/pty/s5 /dev/ttyp5
    test -e /dev/ttyp6 || ln -s /dev/pty/s6 /dev/ttyp6
    test -e /dev/ttyp7 || ln -s /dev/pty/s7 /dev/ttyp7
    test -e /dev/ttyp8 || ln -s /dev/pty/s8 /dev/ttyp8
    test -e /dev/ttyp9 || ln -s /dev/pty/s9 /dev/ttyp9
    test -e /dev/ttypa || ln -s /dev/pty/s10 /dev/ttypa
    test -e /dev/ttypb || ln -s /dev/pty/s11 /dev/ttypb
    test -e /dev/ttypc || ln -s /dev/pty/s12 /dev/ttypc
    test -e /dev/ttypd || ln -s /dev/pty/s13 /dev/ttypd
    test -e /dev/ttype || ln -s /dev/pty/s14 /dev/ttype
    test -e /dev/ttypf || ln -s /dev/pty/s15 /dev/ttypf
else
    exit 1
fi

exit 0
