#! /bin/sh

# Network is configured
if [ -n "`cat /proc/net/dev | sed -e "s/lo://" | grep "[a-z0-9]*:[ ]*[0-9]*"`"  ]; then
    if [ -n "`grep -v '^Iface' /proc/net/route | grep '^eth[0-9]'`" ]; then
        if [ ! -x "/usr/sbin/debootstrap" ]; then
            exit 0
        fi
    fi
fi

# A CD-ROM has been mounted
if [ -e "/cdrom/.disk/info" ]; then
    exit 0
fi

# FIXME: How do we know if a user wants to use a floppy? :)

exit 1
