#!/usr/bin/env python

from optparse import OptionParser
import parallel

def bstr(value):
    stanza = [0,0,0,0,0,0,0,0]
    for i in range(8):
        stanza[7-i] = value & (1 << i) and "1" or "0"
    return "".join(stanza)

parser = OptionParser(usage="parallel-control <options> arg1")
parser.add_option("-o", "--power-on", dest="on_port",
                  help="power on the machine NUMBER", metavar="NUMBER")
parser.add_option("-f", "--power-off", dest="off_port",
                  help="power off the machine NUMBER", metavar="NUMBER")
parser.add_option("-s", "--status", dest="status_port",
                  help="get the status of machine NUMBER", metavar="NUMBER")

(options, args) = parser.parse_args()

port = parallel.Parallel()
value = port.PPRDATA()
if options.on_port:
    machine = int(options.on_port)
    print "Machine %s now is ON." % machine
    value |= 1<<(machine-1)

if options.off_port:
    machine = int(options.off_port)
    print "Machine %s now is power OFF." % machine
    value &= ~(1<<machine-1)

port.setData(value)

if options.status_port:
    machine = int(options.status_port)
    status = int(bstr(value)[8-machine]) and "ON" or "OFF"
    print "Current status of machine %s is %s." % (machine, status)
