#!/bin/sh
# serialize parallel requests
set -e

if [ "$1" = on ]; then
	switch=-o
else
	switch=-f
fi

LOCK=$STATE_DIR/parallel

if [ -z "$PARALLEL_POWER_PIN" ]; then
	echo "PARALLEL_POWER_PIN required for parallel control" >&2
	exit 1
fi

sigout () {
	lockfile-remove $LOCK
}

trap sigout INT QUIT

lockfile-create $LOCK
lockfile-touch --oneshot $LOCK

parallel-control $switch $PARALLEL_POWER_PIN

lockfile-remove $LOCK
