#!/bin/sh
#
# From languagemap in languagechooser
#
# Usage:
#   COUNTRYCODE="countrycode"
#   . countrycodemap

for list in /etc/iso_3166.tab ; do 
    if [ -f "$list" ] ; then
	countries="$list"
    fi
done

line=`grep "$COUNTRYCODE" $countries`

if [ "$line" ] ; then
    set $line

    if [ "$2" ] ; then COUNTRYNAME="$2"; fi

else
    echo "error: Unable to locate info on country '$COUNTRYCODE'"
fi
