#!/bin/sh
#
# From languagemap in languagechooser
#
# Usage:
#   COUNTRYNAME="countryname"
#   . countrymap

for list in /etc/iso_3166.tab ; do 
    if [ -f "$list" ] ; then
	countries="$list"
    fi
done

# The prefered locale (sent to base-config)
LOCALE=C

# The assumed country (location)
COUNTRY=us

# echo "Looking up '$LANGNAME'"

line=`grep "$COUNTRYNAME$" $countries`
#echo L: $line 1>&2

if [ "$line" ] ; then
#    OLD_IFS="$IFS"
#    IFS=';'
    set $line
#    IFS="$OLD_IFS"

    #echo "C: $*"

    if [ "$1" ] ; then COUNTRYCODE="$1"; fi

else
    echo "error: Unable to locate info on country '$COUNTRYNAME'"
fi
