#!/bin/sh
#
# Get the SUPPORTED list of locales
set -e
[ -r /usr/share/i18n/SUPPORTED ] || exit 1
rm -rf debian/SUPPORTED-short >/dev/null 2>&1
cat /usr/share/i18n/SUPPORTED| cut -b 1-5 |uniq >debian/SUPPORTED-short
