#!/bin/sh
#
# Script for generating a debconf templates file from both files
# in debian/po/*.po and country names translations from the
# iso-codes package
#
# Some variables
ISO3166TAB=/usr/share/iso-codes/iso-3166.tab
# Translations location (relative to the build root directory)
ISO3166TRANSLATIONS=debian/iso-codes

# First of all, we build the choices list from the iso 3166 table
# from the iso-codes packages
# The "&" character needs escaping
# We need to replace all commas by something : ' -'
# as the comma is the choices list separator for debconf templates
CHOICES=`cat $ISO3166TAB | \
	 cut -b 4- | \
	 sort | \
         sed 's/\&/\\\\\\\\\&/g' | \
         sed 's/,/ -/g' | \
         (read a; echo -n "$a"; while read b; do echo -n ", $b"; done; echo)`

# If the above fails, the following also works
# CHOICES=`cat ../$ISO3166TRANSLATIONS/iso-3166.tab | sed 's/\&/\\\\\\\\\&/g' | sed 's/,/ - /g' |cut -f2 -d"	" | awk 'BEGIN { FS = "\n" } { printf NR == 1 ? "%s" : ",%s", $1 } END { printf "\n" }'`

# Now put this list as the choices in the templates
# and defined this field as translatable (__Choices hack)
cat debian/templates-in | \
    sed "s/@countrylist@/$CHOICES/g" | \
    sed "s/Choices:/__Choices:/g" \
    >debian/templates.tmp


# Create a temporary "pobuild" directory
rm -rf debian/pobuild >/dev/null 2>&1
mkdir debian/pobuild

# Create the appropriate POTFILES.in file there
cat >debian/pobuild/POTFILES.in <<EOF
[type: gettext/rfc822deb] templates.tmp
EOF

# Create the appropriate output file also
cat >debian/pobuild/output <<EOF
2   utf8
EOF

# Run debconf-updatepo on this directory
# -->this will create pobuild/templates.pot
debconf-updatepo --podir debian/pobuild

# The following takes place for each language
# (each existing file in debian/po
for pofile in debian/po/*.po ; do
    pofilename=`basename $pofile`
    # If the country names are translated, we need to merge
    # the translation with the templates translations
    if [ -f $ISO3166TRANSLATIONS/`basename $pofile` ]
    then
	# the temporary po files will be UTF-8 encoded
	# We put back commas in msgid's
	cat debian/pobuild/templates.pot | 
	    sed '/^\"Content-Type/s/CHARSET/UTF-8/' | 
	    sed '/^msgid/s/ -/,/' \
	    >debian/pobuild/$pofilename.temp
	
	cp debian/pobuild/$pofilename.temp debian/pobuild/templates.pot.temp

	msgmerge -C debian/po/$pofilename \
                 -C $ISO3166TRANSLATIONS/$pofilename \
                 debian/pobuild/$pofilename.temp \
                 debian/pobuild/templates.pot.temp | \
                 sed '/^msgid/s/,/ -/' \
		 > debian/pobuild/$pofilename
    # Else we just use what's translated
    else
	cp $pofile pobuild/$pofilename
    fi
done

# and now we generate the templates file from all this
po2debconf --podir debian/pobuild debian/templates.tmp >debian/templates
