#! /bin/sh -e
#
# Copy install logs to /target/var/log/debian-installer

logsavedir=/target/var/log/debian-installer

test -d $logsavedir || mkdir $logsavedir
cp /var/log/* $logsavedir

# Copy current debconf database
cp -a /var/lib/cdebconf $logsavedir
