#!/bin/sh
#
# Prepare to run base-config after reboot

set -e

ARCH=`udpkg --print-architecture`

. /usr/share/debconf/confmodule

if db_get mirror/distribution && [ "$RET" ] ; then
    SUITE="$RET"

# This code try to fix bug #177459, but fail to work on CDROM installs
# as /cdrom/ is umounted at this point.
#    if [ -f /cdrom/.disk/base_installable ] ; then
#	SUITE=`sed -n 's/^Suite: *//p' /cdrom/dists/$SUITE/Release`
#    else
#	db_get mirror/protocol
#	PROTOCOL="$RET"
#
#	db_get mirror/$PROTOCOL/hostname
#	MIRROR="$RET"
#
#	db_get mirror/$PROTOCOL/directory
#	DIRECTORY="$RET"
#
#	if [ "$PROTOCOL" = "http" ]; then
#            # try to find http proxy
#	    db_get mirror/http/proxy
#	    http_proxy="$RET" || true
#	    if [ "$http_proxy" ]; then
#		export http_proxy
#	    fi
#	fi
#
#	SUITE=`wget -O - ${PROTOCOL}://${MIRROR}${DIRECTORY}/dists/$SUITE/Release | sed -n 's/^Suite: *//p'`
#    fi
fi

# Look in /proc/cmdline for console=ttyS*, indicating a serial console
# and fix inittab if so.
console=$( echo " " $( cat /proc/cmdline ) " " | sed -n 's/^.* console=\([^ ]*\) .*$/\1/p' )
if ( echo "$console" | grep -q "^ttyS" )
then
    # serial console, fix inittab and /etc/securetty.  This edits the
    # ttyS0 entry for whichever ttySn is used, rather than trying to
    # enable the right one.  Allows for ttySn for n>1 that way.
    ttyspeed=$( echo "$console" | sed -n 's/^[^,]*,\([0-9]\+\).*$/\1/p' )
    ttyname=$( echo "$console" | sed 's/,.*//' )
    ttyline=$( echo "$ttyname" | sed 's/^ttyS//' )
    ttyterm=$TERM
    [ -z "$ttyterm" ] && ttyterm=vt100
    [ -z "$ttyspeed" ] && ttyspeed=9600
    cat /target/etc/inittab | sed \
        -e "s/^\([1-6]\):/#\1:/" \
	-e "s/^#T0\(.*ttyS\).*/T$ttyline\1$ttyline $ttyspeed $ttyterm/" \
            > /target/etc/inittab.real
    echo "# $ttyname added by debian-installer" >> /target/etc/securetty
    echo "$ttyname" >> /target/etc/securetty
else
    # graphical console, leave inittab alone
    mv /target/etc/inittab /target/etc/inittab.real
fi

cp /usr/share/prebaseconfig/inittab /target/etc/inittab

(
    echo "# inserted by prebaseconfig"
    echo "SUITE=\"$SUITE\""
) >> /target/root/dbootstrap_settings

