#! /bin/sh
#
# Copy install logs to /target/var/log/debian-installer

set -e

logsavedir=/target/var/log/debian-installer

test -d $logsavedir || mkdir $logsavedir
cp /var/log/* $logsavedir

# Copy current debconf database
cp -a /var/lib/cdebconf $logsavedir
