#! /bin/sh -e
#
# Reboot the system, and ask the user to wait while this happens

. /usr/share/debconf/confmodule

# In case some file systems are still mounted
sync; sync; sync

db_input critical prebaseconfig/reboot_in_progress || true
db_go || true
db_fset prebaseconfig/reboot_in_progress seen false || true

db_progress START 0 1 prebaseconfig/progress/title

/sbin/reboot

db_progress STEP 1
db_progress STOP
