#!/bin/sh
# Use this as a PREBOOT command if you're netbooting something else
# along with d-i. This sets a symlink to point to the thing to boot.
# In dhcpd.conf you might put:
#   filename "/ia64-boot/elilo.efi";
# Then set NETBOOT_IMAGE to point to the directory containing the elilo.efi
# that you want to boot, and the ia64-boot link will be pointed to that
# directory by this script.
set -e
cd $TFTP_DIR
if [ -e $ARCH-boot ]; then
	rm $ARCH-boot
fi
ln -sf $NETBOOT_IMAGE_DIR $ARCH-boot
