#!/bin/sh
# Runs qemu, booting from disk.
set -e

if [ -n "$QEMU_COMMAND" ]; then
	QEMU_COMMAND=qemu
fi

rm -f $STATE_DIR/qemu-$MACHINE-$SCHEME.pid
$QEMU_COMMAND -daemonize -pidfile $STATE_DIR/qemu-$MACHINE-$SCHEME.pid \
	--cdrom "$ISO" \
	-hda $STATE_DIR/qemu-$MACHINE-$SCHEME.img \
	-nographic \
	-net nic -net user,hostname=qemu \
	-boot c -no-reboot \
	$QEMU_EXTRA_PARAMS \
	-serial tcp:localhost:$QEMU_SERIAL_PORT,server &
