#!/bin/sh

rc=$DI_TESTDIR/state/bochs-$MACHINE-$SCHEME.bochsrc

# Store the pid so stopbochs can stop it later.
echo "$$" > $DI_TESTDIR/state/bochs-$MACHINE-$SCHEME.pid
# Run bochs-bin since the bochs wrapper script does not propigate kill
# signals to bochs-bin.
exec bochs-bin -qf $rc
