#!/bin/sh
# Start bochs, but first store the pid so stopbochs can stop it later.
echo "$$" > $DI_TESTDIR/state/bochs-$MACHINE-$SCHEME.pid
# Run bochs-bin since the bochs wrapper script does not propigate kill
# signals to bochs-bin.
exec bochs-bin -q $@
