#!/bin/sh
# Runs qemu, booting from disk on mips(el).
set -e

if [ -z "$QEMU_COMMAND" ]; then
	QEMU_COMMAND=qemu
fi

# Qemu needs a dummy bios file for mips.
mkdir -p $STATE_DIR/qemu-$MACHINE-$SCHEME.files
dd if=/dev/zero of=$STATE_DIR/qemu-$MACHINE-$SCHEME.files/mips_bios.bin bs=1024 count=128

# Store the pid so stopqemu can stop it later.
echo "$$" > $STATE_DIR/qemu-$MACHINE-$SCHEME.pid
exec $QEMU_COMMAND \
	-kernel $NETBOOT_KERNEL \
	-hda $STATE_DIR/qemu-$MACHINE-$SCHEME.img \
	-boot c \
	-append "root=$ROOTDEV" \
	-nographic \
	-L $STATE_DIR/qemu-$MACHINE-$SCHEME.files \
	-net nic -net user,hostname=$MACHINE \
	-no-reboot \
	$QEMU_EXTRA_PARAMS \
	-serial tcp:localhost:$QEMU_SERIAL_PORT,server 
