#!/bin/sh
set -e
count=0
while ! telnet localhost $QEMU_SERIAL_PORT; do
	count=$(expr $count + 1)
	sleep 1
	if [ "$count" = 10 ]; then
		echo "Error: could not connect over $count tries" >&2
		exit 1
	fi
	echo "Retrying connection.."
done
