#!/bin/sh -e

. /usr/share/debconf/confmodule

FLOPPYMNT=/floppy

db_capb BACKUP

# FIXME FIXME FIXME
mountfloppy()
{
    if ! mount | cut -d' ' -f3 | grep -q '^/floppy$'; then
        if [ ! -d /dev/floppy ]; then
            modprobe floppy >> /var/log/messages 2>&1
        fi
        if [ ! -d /dev/floppy ]; then
            exit 1
        fi
        if ! grep -q ^vfat /proc/modules ; then
            modprobe vfat >> /var/log/messages 2>&1
        fi

        STATE=1
        while [ "$STATE" != 0 -a "$STATE" != 3 ]; do
            case "$STATE" in
            1)
                db_fset retriever/floppy/insert seen false || true
                db_fset retriever/floppy/fstype seen false || true
                db_input critical retriever/floppy/insert || true
                db_input low retriever/floppy/fstype || true
                ;;
            2)
                db_get retriever/floppy/fstype
                if [ "$RET" = "Enter manually" ]; then
                    db_input critical retriever/floppy/fstype-manual || true
                fi
                ;;
            esac
            if db_go; then
                STATE=$(($STATE + 1))
            else
                STATE=$(($STATE - 1))
            fi
        done
        if [ "$STATE" = 0 ]; then
            exit 30 # backed out
        fi
        db_capb

        mount /dev/floppy/0 -tauto $FLOPPYMNT
    fi
}

cmd="$1"
shift

case "x$cmd" in
    xconfig)
        mountfloppy
        for f in include exclude; do
            if [ -e $FLOPPYMNT/udeb_$f ]; then
                ln -sf $FLOPPYMNT/udeb_$f /var/cache/anna/$f
            fi
        done
        ;;

    xretrieve)
        mountfloppy
        if [ -e $FLOPPYMNT/$1 ]; then
            ln -sf $FLOPPYMNT/$1 "$2"
            exit $?
        else
            exit 1
        fi
        ;;

    xpackages)
        # generate a Packages file based on what udebs are on the floppy
        if [ "$2" != "." ]; then
            # sorry, no compressed files
            exit 1
        fi
        if [ -n "$3" -a "$3" != "main" ]; then
            # only do 'main'
            exit 1
        fi
        mountfloppy
        rm -f "$1"
        touch "$1"
        # Check for regular debs, udebs, and to be on the safe side,
        # check for *.ude files (msdos file names...)
        for filename in $FLOPPYMNT/*.{deb,udeb,ude}; do
            if [ -f "$filename" ]; then
                udpkg -f "$filename" >> "$1"
                path="`echo "$filename" | sed 's,^/floppy/,,'`"
                echo "Filename: $path" >> "$1"
                echo >> "$1"
            fi
        done
        ;;

    xcleanup)
        umount $FLOPPYMNT || true
        ;;

    *)
        # unknown command
        exit 1
        ;;
esac
