#!/bin/sh -e

. /usr/share/debconf/confmodule

FLOPPYMNT=/floppy

mountfloppy()
{
    if ! mount | cut -d' ' -f3 | grep -q '^/floppy$'; then
	# The INSTALL_MEDIA_DEV is set by the linuxrc on the boot
	# floppy to the device it loaded the initrd from. It's also
	# documented so the user may set it at the boot prompt.
	# That is (probably) the floppy drive, which may be a USB floppy.
	if [ -n "$INSTALL_MEDIA_DEV" ]; then
	    FLOPPYDEV=$INSTALL_MEDIA_DEV
        else
	    # XXX not ideal. Fails if the floppy is USB.
	    FLOPPYDEV=/dev/floppy/0
	fi
	    
        if [ ! -e $FLOPPYDEV ]; then
            modprobe floppy >> /var/log/messages 2>&1 || true
        fi
        if [ ! -e $FLOPPYDEV ]; then
            exit 1
        fi
        if ! grep -q ^vfat /proc/modules ; then
            modprobe vfat >> /var/log/messages 2>&1 || true
        fi

        mount $FLOPPYDEV -tauto $FLOPPYMNT
    fi
}

cmd="$1"
shift

case "x$cmd" in
    xconfig)
        mountfloppy
        for f in include exclude; do
            if [ -e $FLOPPYMNT/udeb_$f ]; then
                ln -sf $FLOPPYMNT/udeb_$f /var/cache/anna/$f
            fi
        done
        ;;

    xretrieve)
        mountfloppy
        if [ -e $FLOPPYMNT/$1 ]; then
            ln -sf $FLOPPYMNT/$1 "$2"
            exit $?
        else
            exit 1
        fi
        ;;

    xpackages)
        # generate a Packages file based on what udebs are on the floppy
        mountfloppy
        rm -f "$1"
        touch "$1"
        # Check for regular debs, udebs, and to be on the safe side,
        # check for *.ude files (msdos file names...)
	FILES=""
	FILE_COUNT=0
        for filename in $FLOPPYMNT/*.deb $FLOPPYMNT/*.udeb $FLOPPYMNT/*.ude; do
            if [ -f "$filename" ]; then
	    	FILES="$FILES $filename"
		FILE_COUNT=$(expr $FILE_COUNT + 1)
	    fi
	done
	if [ "$FILE_COUNT" = 0 ]; then
		# Probably not a legitimate driver floppy.
		exit 1
	fi
	# This could take a while, so a progress bar.
	db_progress START 0 $FILE_COUNT retriever/floppy/packages/progress
	for filename in $FILES; do
            udpkg -f "$filename" >> "$1"
            path="`echo "$filename" | sed 's,^/floppy/,,'`"
            echo "Filename: $path" >> "$1"
            echo >> "$1"
	    db_progress STEP 1
        done
	db_progress STOP
        ;;

    xcleanup)
        umount $FLOPPYMNT || true
        ;;

    *)
        # unknown command
        exit 1
        ;;
esac
