#!/bin/sh

. /lib/partman/definitions.sh

for dev in $DEVICES/*; do
    [ -d "$dev" ] || continue
    cd $dev
    partitions=
    open_dialog PARTITIONS
    while { read_line num id size type fs path name; [ "$id" ]; }; do
	[ "$fs" != free ] || continue
        partitions="$partitions $id,$num"
    done
    close_dialog
    
    for part in $partitions; do
        id=${part%,*}
        num=${part#*,}
	[ -f $id/method -a -f $id/format \
	    -a -f $id/acting_filesystem ] || continue
	filesystem=$(cat $id/acting_filesystem)
	case $filesystem in
	    reiserfs)
		log "Try to create file system for $dev/$id"
		open_dialog PARTITION_INFO $id
		read_line x1 x2 x3 x4 x5 device x6
		close_dialog
		db_subst partman-reiserfs/progress_formatting TYPE "$filesystem"
		db_subst partman-reiserfs/progress_formatting PARTITION "$num"
		db_subst partman-reiserfs/progress_formatting DEVICE $(humandev $(cat device))
		# TODO let parted try to do it, fallback on failure
		mkreiserfs -f -q $device >/dev/null 2>>/var/log/messages
		code=$?
		db_progress STOP
		if [ "$code" != 0 ]; then
		    db_fset partman-reiserfs/create_failed seen false
		    db_subst partman-reiserfs/create_failed PARTITION "$num"
		    db_subst partman-reiserfs/create_failed DEVICE $(humandev $(cat device))
		    db_input critical partman-reiserfs/create_failed || true
		    db_go || true
		    exit 1
		fi
		;;
	esac
    done
done
