#!/usr/bin/perl

=head1 NAME

dh_di_installchangelogs - install changelogs into package build directories

dh_di_installdocs - install documentation into package build directories

dh_di_makeshlibs - automatically create shlibs file

dh_di_md5sums - generate DEBIAN/md5sums file

=cut

use strict;
use warnings;

use Debian::Debhelper::Dh_Lib;
use Debian::Installer;
use File::Basename;

=head1 SYNOPSIS

B<dh_di_installchangelogs> [S<I<debhelper options>>] [S<I<di_installchangelogs options>>]

B<dh_di_installdocs> [S<I<debhelper options>>] [S<I<di_installdocs options>>]

B<dh_di_makeshlibs> [S<I<debhelper options>>] [S<I<di_makeshlibs options>>]

B<dh_di_md5sums> [S<I<debhelper options>>] [S<I<di_md5sums options>>]

=head1 DESCRIPTION

Wrappers arround the debhelper commands which only affects debs.

=cut

my @args = Debian::Installer::fixup_arguments (@ARGV);

init();

my %packages = Debian::Installer::control();
my @args2 = Debian::Installer::packages_args ("deb", \%packages, @{$dh{DOPACKAGES}});

my $prog = basename($0);
if ($prog =~ m#^dh_di_(\w+)$#)
{
  doit ("dh_$1", @args2, @args);
}
else
{
  exit 1;
}

=head1 SEE ALSO

L<dh_installchangelogs(1)>
L<dh_installdocs(1)>
L<dh_makeshlibs(1)>
L<dh_md5sum(1)>
L<debhelper(7)>

=head1 AUTHOR

Bastian Blank <waldi@debian.org>

=cut

