#!/bin/sh -e

. /lib/partman/definitions.sh

dev="$2"
cd $dev

open_dialog LABEL_TYPES
types=$(read_list)
close_dialog

db_fset partman-partitioning/choose_label seen false
db_subst partman-partitioning/choose_label CHOICES "$types"
PRIORITY=high
default_label=$(default_disk_label)
if expr "$types" : ".*${default_label}.*" >/dev/null; then
	db_set partman-partitioning/choose_label "$default_label"
	PRIORITY=low
fi
db_input $PRIORITY partman-partitioning/choose_label || true
db_go || exit 1
db_get partman-partitioning/choose_label

open_dialog NEW_LABEL "$RET"
close_dialog

# Different types partition tables support different visuals.  Some
# have partition names other don't have, some have extended and
# logical partitions, others don't.  Hence we have to regenerate the
# list of the visuals
if [ -f visuals ]; then
    rm visuals
fi

partitions=''
open_dialog PARTITIONS
while { read_line num id size type fs path name; [ "$id" ]; }; do
    partitions="$partitions $id"
done
close_dialog

for id in $partitions; do
    update_partition $dev $id
done
